# Getting the data

In [5]:
import pandas as pd

In [6]:
from nba_api.stats.endpoints import teamgamelogs

In [1253]:
df = teamgamelogs.TeamGameLogs(season_nullable="1999-00").get_data_frames()[0]

In [1254]:
df.columns

Index(['SEASON_YEAR', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME', 'GAME_ID',
       'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M',
       'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST',
       'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', 'PTS', 'PLUS_MINUS',
       'GP_RANK', 'W_RANK', 'L_RANK', 'W_PCT_RANK', 'MIN_RANK', 'FGM_RANK',
       'FGA_RANK', 'FG_PCT_RANK', 'FG3M_RANK', 'FG3A_RANK', 'FG3_PCT_RANK',
       'FTM_RANK', 'FTA_RANK', 'FT_PCT_RANK', 'OREB_RANK', 'DREB_RANK',
       'REB_RANK', 'AST_RANK', 'TOV_RANK', 'STL_RANK', 'BLK_RANK', 'BLKA_RANK',
       'PF_RANK', 'PFD_RANK', 'PTS_RANK', 'PLUS_MINUS_RANK'],
      dtype='object')

In [1260]:
season_list = []

for i in range((9)):
    season = "200" + str(i) + "-0" + str(i+1)
    season_list.append(season)
    
season_list.append("2009-10")

for i in range((9)):
    season = "201" + str(i) + "-1" + str(i+1)
    season_list.append(season)
    
season_list.append("2019-20")
season_list.append("2020-21")
season_list.append("2021-22")

In [1261]:
season_list

['2000-01',
 '2001-02',
 '2002-03',
 '2003-04',
 '2004-05',
 '2005-06',
 '2006-07',
 '2007-08',
 '2008-09',
 '2009-10',
 '2010-11',
 '2011-12',
 '2012-13',
 '2013-14',
 '2014-15',
 '2015-16',
 '2016-17',
 '2017-18',
 '2018-19',
 '2019-20',
 '2020-21',
 '2021-22']

In [1262]:
df

,SEASON_YEAR,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK
0,1999-00,1610612764,WAS,Washington Wizards,0029901182,2000-04-19T00:00:00,WAS @ MIL,L,48.0,39,...,927,626,261,2077,1656,1432,2139,1566,587,1461
1,1999-00,1610612766,CHH,Charlotte Hornets,0029901179,2000-04-19T00:00:00,CHH vs. MIA,W,48.0,31,...,2253,497,261,1574,1989,34,5,1011,2102,494
2,1999-00,1610612744,GSW,Golden State Warriors,0029901187,2000-04-19T00:00:00,GSW vs. PHX,L,48.0,32,...,1755,626,1238,111,948,1081,237,1011,1845,1886
3,1999-00,1610612747,LAL,Los Angeles Lakers,0029901185,2000-04-19T00:00:00,LAL @ SAS,L,53.0,41,...,32,941,261,2077,1656,724,867,1011,1113,1461
4,1999-00,1610612763,VAN,Vancouver Grizzlies,0029901184,2000-04-19T00:00:00,VAN @ HOU,W,48.0,35,...,1068,1654,814,944,1299,1724,93,2118,1232,919
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2373,1999-00,1610612739,CLE,Cleveland Cavaliers,0029900001,1999-11-02T00:00:00,CLE @ NYK,L,48.0,30,...,1755,941,1839,467,1989,2198,1811,1011,2062,1676
2374,1999-00,1610612761,TOR,Toronto Raptors,0029900006,1999-11-02T00:00:00,TOR vs. BOS,L,48.0,33,...,1990,1130,1456,668,447,724,515,1011,1704,1979
2375,1999-00,1610612762,UTA,Utah Jazz,0029900011,1999-11-02T00:00:00,UTA vs. LAL,L,48.0,29,...,1755,1494,1655,1240,656,1432,1638,284,2062,1607
2376,1999-00,1610612738,BOS,Boston Celtics,0029900006,1999-11-02T00:00:00,BOS @ TOR,W,48.0,38,...,1627,1298,1655,186,1299,1724,2139,1011,708,354
2377,1999-00,1610612755,PHI,Philadelphia 76ers,0029900009,1999-11-02T00:00:00,PHI @ SAS,L,48.0,30,...,2088,2168,616,467,948,2315,1089,135,2303,1979

In [1371]:
import time

def getData(season_list):
    df = teamgamelogs.TeamGameLogs(season_nullable=season_list[0], measure_type_player_game_logs_nullable="Four Factors").get_data_frames()[0]
    time.sleep(.3)
    playoff_df = teamgamelogs.TeamGameLogs(season_nullable=season_list[0], season_type_nullable="Playoffs", measure_type_player_game_logs_nullable="Four Factors").get_data_frames()[0]
    time.sleep(.3)
    df=df.append(playoff_df)

    
    print(f"Four factors for {season_list[0]} is done")
    for i in range(len(season_list)-1):
        df_temp = teamgamelogs.TeamGameLogs(season_nullable=season_list[i+1],measure_type_player_game_logs_nullable="Four Factors").get_data_frames()[0]
        time.sleep(.3)
        playoff_df = teamgamelogs.TeamGameLogs(season_nullable=season_list[i+1], season_type_nullable="Playoffs",measure_type_player_game_logs_nullable="Four Factors").get_data_frames()[0]
        df=df.append(df_temp)
        df=df.append(playoff_df)
        print(f"Four factors for {season_list[i+1]} is done")
        time.sleep(1)

        
        
    df_PTS = teamgamelogs.TeamGameLogs(season_nullable=season_list[0]).get_data_frames()[0]
    time.sleep(.3)
    playoff_df_PTS = teamgamelogs.TeamGameLogs(season_nullable=season_list[0], season_type_nullable="Playoffs").get_data_frames()[0]
    time.sleep(.3)
    df_PTS=df_PTS.append(playoff_df_PTS)
    df_PTS['PTS_SEASON_RANK'] = df_PTS['PTS'].rank(ascending=False)
    print(f"Points for {season_list[0]} is done")
    for i in range(len(season_list)-1):
        df_PTS_temp = teamgamelogs.TeamGameLogs(season_nullable=season_list[i+1]).get_data_frames()[0]
        time.sleep(.3)
        playoff_df_PTS = teamgamelogs.TeamGameLogs(season_nullable=season_list[i+1], season_type_nullable="Playoffs").get_data_frames()[0]
        df_PTS_temp = df_PTS_temp.append(playoff_df_PTS)
        
        df_PTS_temp['PTS_SEASON_RANK'] = df_PTS_temp['PTS'].rank(ascending=False)
        df_PTS = df_PTS.append(df_PTS_temp)
        print(f"Points for {season_list[i+1]} is done")
        time.sleep(1)
  

    df_PTS = df_PTS[["PTS",'PTS_SEASON_RANK',"GAME_ID","TEAM_ID"]]
    df = df.merge(df_PTS, how='left', on=['GAME_ID','TEAM_ID'])
        
    return df

In [7]:
df = getData(season_list)
df.to_csv("TrainingDataFF.csv")

NameError: name 'getData' is not defined

In [9]:
df = pd.read_csv("TrainingDataFF.csv")

In [10]:
df

,Unnamed: 0,SEASON_YEAR,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,...,EFG_PCT_RANK,FTA_RATE_RANK,TM_TOV_PCT_RANK,OREB_PCT_RANK,OPP_EFG_PCT_RANK,OPP_FTA_RATE_RANK,OPP_TOV_PCT_RANK,OPP_OREB_PCT_RANK,PTS,PTS_SEASON_RANK
0,0,2000-01,1610612744,GSW,Golden State Warriors,20001188,2001-04-18T00:00:00,GSW vs. VAN,L,48.0,...,2369,1627,1427,1,518,546,1225,2341,81,2221.5
1,1,2000-01,1610612755,PHI,Philadelphia 76ers,20001181,2001-04-18T00:00:00,PHI vs. CHI,L,48.0,...,1457,1715,2052,378,1856,1707,1870,47,86,1931.5
2,2,2000-01,1610612754,IND,Indiana Pacers,20001184,2001-04-18T00:00:00,IND @ CLE,W,53.0,...,839,2056,1448,1875,327,729,2269,812,105,466.0
3,3,2000-01,1610612766,CHH,Charlotte Hornets,20001179,2001-04-18T00:00:00,CHH @ BOS,W,48.0,...,1734,834,1246,277,761,1282,1588,834,97,1076.5
4,4,2000-01,1610612753,ORL,Orlando Magic,20001183,2001-04-18T00:00:00,ORL vs. MIA,L,48.0,...,883,1807,1846,1426,1530,774,1339,2257,91,1566.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56257,56257,2021-22,1610612742,DAL,Dallas Mavericks,42100171,2022-04-16T00:00:00,DAL vs. UTA,L,48.0,...,115,8,4,111,30,72,49,118,93,2370.5
56258,56258,2021-22,1610612761,TOR,Toronto Raptors,42100131,2022-04-16T00:00:00,TOR @ PHI,L,48.0,...,47,53,7,62,110,113,125,81,111,1233.0
56259,56259,2021-22,1610612755,PHI,Philadelphia 76ers,42100131,2022-04-16T00:00:00,PHI vs. TOR,W,48.0,...,17,14,2,46,79,74,120,65,131,152.0
56260,56260,2021-22,1610612750,MIN,Minnesota Timberwolves,42100151,2022-04-16T00:00:00,MIN @ MEM,W,48.0,...,27,44,103,32,38,123,96,51,130,176.5
56261,56261,2021-22,1610612743,DEN,Denver Nuggets,42100161,2022-04-16T00:00:00,DEN @ GSW,L,48.0,...,72,122,36,24,113,96,72,106,107,1562.0

In [11]:
df.columns

Index(['Unnamed: 0', 'SEASON_YEAR', 'TEAM_ID', 'TEAM_ABBREVIATION',
       'TEAM_NAME', 'GAME_ID', 'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'EFG_PCT',
       'FTA_RATE', 'TM_TOV_PCT', 'OREB_PCT', 'OPP_EFG_PCT', 'OPP_FTA_RATE',
       'OPP_TOV_PCT', 'OPP_OREB_PCT', 'GP_RANK', 'W_RANK', 'L_RANK',
       'W_PCT_RANK', 'MIN_RANK', 'EFG_PCT_RANK', 'FTA_RATE_RANK',
       'TM_TOV_PCT_RANK', 'OREB_PCT_RANK', 'OPP_EFG_PCT_RANK',
       'OPP_FTA_RATE_RANK', 'OPP_TOV_PCT_RANK', 'OPP_OREB_PCT_RANK', 'PTS',
       'PTS_SEASON_RANK'],
      dtype='object')

In [12]:
# match games together

test_df = df.groupby("GAME_ID")

In [13]:
test_df = test_df.get_group(20001181)

In [14]:
test_df

,Unnamed: 0,SEASON_YEAR,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,...,EFG_PCT_RANK,FTA_RATE_RANK,TM_TOV_PCT_RANK,OREB_PCT_RANK,OPP_EFG_PCT_RANK,OPP_FTA_RATE_RANK,OPP_TOV_PCT_RANK,OPP_OREB_PCT_RANK,PTS,PTS_SEASON_RANK
1,1,2000-01,1610612755,PHI,Philadelphia 76ers,20001181,2001-04-18T00:00:00,PHI vs. CHI,L,48.0,...,1457,1715,2052,378,1856,1707,1870,47,86,1931.5
7,7,2000-01,1610612741,CHI,Chicago Bulls,20001181,2001-04-18T00:00:00,CHI @ PHI,W,48.0,...,521,672,501,2329,918,657,323,1996,92,1483.0

In [15]:
row = pd.concat([test_df.iloc[0], test_df.iloc[1]], axis=0)

In [16]:
row

Unnamed: 0                            1
SEASON_YEAR                     2000-01
TEAM_ID                      1610612755
TEAM_ABBREVIATION                   PHI
TEAM_NAME            Philadelphia 76ers
                            ...
OPP_FTA_RATE_RANK                   657
OPP_TOV_PCT_RANK                    323
OPP_OREB_PCT_RANK                  1996
PTS                                  92
PTS_SEASON_RANK                    1483
Length: 66, dtype: object

In [17]:
df.columns

Index(['Unnamed: 0', 'SEASON_YEAR', 'TEAM_ID', 'TEAM_ABBREVIATION',
       'TEAM_NAME', 'GAME_ID', 'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'EFG_PCT',
       'FTA_RATE', 'TM_TOV_PCT', 'OREB_PCT', 'OPP_EFG_PCT', 'OPP_FTA_RATE',
       'OPP_TOV_PCT', 'OPP_OREB_PCT', 'GP_RANK', 'W_RANK', 'L_RANK',
       'W_PCT_RANK', 'MIN_RANK', 'EFG_PCT_RANK', 'FTA_RATE_RANK',
       'TM_TOV_PCT_RANK', 'OREB_PCT_RANK', 'OPP_EFG_PCT_RANK',
       'OPP_FTA_RATE_RANK', 'OPP_TOV_PCT_RANK', 'OPP_OREB_PCT_RANK', 'PTS',
       'PTS_SEASON_RANK'],
      dtype='object')

In [18]:
def groupGames(df):
    
    game_ids = df["GAME_ID"].unique()
    grouped_df = df.groupby("GAME_ID")

    row_1 = []
    row_2 = []
    for i in range(len(game_ids)):
        group = grouped_df.get_group(game_ids[i])
        if group['PTS'].isna().sum() == 0:
            group["is_home"] = (group["MATCHUP"].str.contains("vs.")).astype("int")
            row_1.append(group.iloc[0])
            row_2.append(group.iloc[1])
        else:
            continue
        
    row_1_df = pd.DataFrame(row_1)
    row_2_df = pd.DataFrame(row_2)
    
    row_1_df = row_1_df.add_prefix('HOME_')
    row_1_df = row_1_df.rename(columns={'HOME_GAME_ID': 'GAME_ID'})
    row_2_df = row_2_df.add_prefix('AWAY_')
    row_2_df = row_2_df.rename(columns={'AWAY_GAME_ID': 'GAME_ID'})
    
    columns1 = ['HOME_SEASON_YEAR','HOME_GAME_DATE','HOME_TEAM_NAME', 'HOME_TEAM_ABBREVIATION','HOME_TEAM_ID','GAME_ID','HOME_WL', 'HOME_EFG_PCT',
       'HOME_FTA_RATE', 'HOME_TM_TOV_PCT', 'HOME_OREB_PCT','HOME_W_PCT_RANK','HOME_PTS','HOME_is_home','HOME_PTS_SEASON_RANK']
    columns2 = ['AWAY_SEASON_YEAR','AWAY_GAME_DATE','AWAY_TEAM_NAME', 'AWAY_TEAM_ABBREVIATION','AWAY_TEAM_ID','GAME_ID','AWAY_WL', 'AWAY_EFG_PCT',
       'AWAY_FTA_RATE', 'AWAY_TM_TOV_PCT', 'AWAY_OREB_PCT','AWAY_W_PCT_RANK','AWAY_PTS','AWAY_is_home','AWAY_PTS_SEASON_RANK']
    
    combined_df_1 = row_1_df[columns1].merge(row_2_df[columns2], 
                                       on="GAME_ID")
    
    
    row_1_df = pd.DataFrame(row_1)
    row_2_df = pd.DataFrame(row_2)
    
    row_2_df = row_2_df.add_prefix('HOME_')
    row_2_df = row_2_df.rename(columns={'HOME_GAME_ID': 'GAME_ID'})
    row_1_df = row_1_df.add_prefix('AWAY_')
    row_1_df = row_1_df.rename(columns={'AWAY_GAME_ID': 'GAME_ID'})
    
 
    
    combined_df_2 = row_2_df[columns1].merge(row_1_df[columns2], on="GAME_ID")

    combined_df = combined_df_1.append(combined_df_2)
    
    
    return combined_df

In [19]:
combined_df = groupGames(df)

<ipython-input-18-3d2d6a7bcd70>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  group["is_home"] = (group["MATCHUP"].str.contains("vs.")).astype("int")

In [20]:
combined_df

,HOME_SEASON_YEAR,HOME_GAME_DATE,HOME_TEAM_NAME,HOME_TEAM_ABBREVIATION,HOME_TEAM_ID,GAME_ID,HOME_WL,HOME_EFG_PCT,HOME_FTA_RATE,HOME_TM_TOV_PCT,...,AWAY_TEAM_ID,AWAY_WL,AWAY_EFG_PCT,AWAY_FTA_RATE,AWAY_TM_TOV_PCT,AWAY_OREB_PCT,AWAY_W_PCT_RANK,AWAY_PTS,AWAY_is_home,AWAY_PTS_SEASON_RANK
0,2000-01,2001-04-18T00:00:00,Golden State Warriors,GSW,1610612744,20001188,L,0.319,0.255,0.169,...,1610612763,W,0.424,0.228,0.157,0.466,1,95,0,1242.0
1,2000-01,2001-04-18T00:00:00,Philadelphia 76ers,PHI,1610612755,20001181,L,0.455,0.244,0.207,...,1610612741,W,0.522,0.368,0.128,0.167,1,92,0,1483.0
2,2000-01,2001-04-18T00:00:00,Indiana Pacers,IND,1610612754,20001184,W,0.495,0.196,0.170,...,1610612739,L,0.404,0.253,0.094,0.279,1190,101,1,743.0
3,2000-01,2001-04-18T00:00:00,Charlotte Hornets,CHH,1610612766,20001179,W,0.435,0.345,0.161,...,1610612738,L,0.444,0.313,0.141,0.280,1190,92,1,1483.0
4,2000-01,2001-04-18T00:00:00,Orlando Magic,ORL,1610612753,20001183,L,0.494,0.231,0.191,...,1610612748,W,0.494,0.258,0.152,0.429,1,103,0,600.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28126,2021-22,2022-04-17T00:00:00,Miami Heat,MIA,1610612748,42100101,W,0.634,0.220,0.155,...,1610612737,L,0.453,0.360,0.186,0.204,64,91,0,2431.5
28127,2021-22,2022-04-16T00:00:00,Dallas Mavericks,DAL,1610612742,42100171,L,0.441,0.447,0.078,...,1610612762,W,0.476,0.277,0.154,0.396,1,99,0,2099.5
28128,2021-22,2022-04-16T00:00:00,Denver Nuggets,DEN,1610612743,42100161,L,0.522,0.140,0.117,...,1610612744,W,0.622,0.354,0.138,0.341,1,123,1,413.5
28129,2021-22,2022-04-16T00:00:00,Minnesota Timberwolves,MIN,1610612750,42100151,W,0.589,0.300,0.178,...,1610612763,L,0.494,0.500,0.114,0.250,64,117,1,760.5
28130,2021-22,2022-04-16T00:00:00,Philadelphia 76ers,PHI,1610612755,42100131,W,0.607,0.405,0.045,...,1610612761,L,0.561,0.280,0.088,0.279,64,111,0,1233.0

In [21]:
combined_df.columns

Index(['HOME_SEASON_YEAR', 'HOME_GAME_DATE', 'HOME_TEAM_NAME',
       'HOME_TEAM_ABBREVIATION', 'HOME_TEAM_ID', 'GAME_ID', 'HOME_WL',
       'HOME_EFG_PCT', 'HOME_FTA_RATE', 'HOME_TM_TOV_PCT', 'HOME_OREB_PCT',
       'HOME_W_PCT_RANK', 'HOME_PTS', 'HOME_is_home', 'HOME_PTS_SEASON_RANK',
       'AWAY_SEASON_YEAR', 'AWAY_GAME_DATE', 'AWAY_TEAM_NAME',
       'AWAY_TEAM_ABBREVIATION', 'AWAY_TEAM_ID', 'AWAY_WL', 'AWAY_EFG_PCT',
       'AWAY_FTA_RATE', 'AWAY_TM_TOV_PCT', 'AWAY_OREB_PCT', 'AWAY_W_PCT_RANK',
       'AWAY_PTS', 'AWAY_is_home', 'AWAY_PTS_SEASON_RANK'],
      dtype='object')

In [22]:
def rolling_averages(group, cols, new_cols, amount):

    group = group.sort_values("HOME_GAME_DATE")
    rolling_stats = group[cols].shift(periods=1).rolling(amount).mean() # the 3 before
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    
    return group

In [23]:
cols = ['HOME_EFG_PCT', 'HOME_FTA_RATE',
       'HOME_TM_TOV_PCT', 'HOME_OREB_PCT', 'HOME_W_PCT_RANK', 'HOME_PTS','HOME_PTS_SEASON_RANK','AWAY_EFG_PCT', 'AWAY_FTA_RATE',
       'AWAY_TM_TOV_PCT', 'AWAY_OREB_PCT', 'AWAY_W_PCT_RANK', 'AWAY_PTS','AWAY_PTS_SEASON_RANK']
new_cols = [f"{c}_rolling_5" for c in cols]

rolling_df = combined_df.groupby("HOME_TEAM_ID").apply(lambda x: rolling_averages(x, cols, new_cols, 3))
rolling_df = rolling_df.droplevel('HOME_TEAM_ID').reset_index().drop('index', axis=1)

In [24]:
cols = ['HOME_EFG_PCT', 'HOME_FTA_RATE',
       'HOME_TM_TOV_PCT', 'HOME_OREB_PCT', 'HOME_W_PCT_RANK', 'HOME_PTS','HOME_PTS_SEASON_RANK','AWAY_EFG_PCT', 'AWAY_FTA_RATE',
       'AWAY_TM_TOV_PCT', 'AWAY_OREB_PCT', 'AWAY_W_PCT_RANK', 'AWAY_PTS','AWAY_PTS_SEASON_RANK']
new_cols = [f"{c}_rolling_15" for c in cols]

rolling_df = rolling_df.groupby("HOME_TEAM_ID").apply(lambda x: rolling_averages(x, cols, new_cols, 15))
rolling_df = rolling_df.droplevel('HOME_TEAM_ID').reset_index().drop('index', axis=1)

# The model, win classifier

In [25]:
rolling_df["target"] = (rolling_df["HOME_WL"] == "W").astype("int") # count draw and loss as not a win

In [26]:
print(rolling_df.columns.tolist())

['HOME_SEASON_YEAR', 'HOME_GAME_DATE', 'HOME_TEAM_NAME', 'HOME_TEAM_ABBREVIATION', 'HOME_TEAM_ID', 'GAME_ID', 'HOME_WL', 'HOME_EFG_PCT', 'HOME_FTA_RATE', 'HOME_TM_TOV_PCT', 'HOME_OREB_PCT', 'HOME_W_PCT_RANK', 'HOME_PTS', 'HOME_is_home', 'HOME_PTS_SEASON_RANK', 'AWAY_SEASON_YEAR', 'AWAY_GAME_DATE', 'AWAY_TEAM_NAME', 'AWAY_TEAM_ABBREVIATION', 'AWAY_TEAM_ID', 'AWAY_WL', 'AWAY_EFG_PCT', 'AWAY_FTA_RATE', 'AWAY_TM_TOV_PCT', 'AWAY_OREB_PCT', 'AWAY_W_PCT_RANK', 'AWAY_PTS', 'AWAY_is_home', 'AWAY_PTS_SEASON_RANK', 'HOME_EFG_PCT_rolling_5', 'HOME_FTA_RATE_rolling_5', 'HOME_TM_TOV_PCT_rolling_5', 'HOME_OREB_PCT_rolling_5', 'HOME_W_PCT_RANK_rolling_5', 'HOME_PTS_rolling_5', 'HOME_PTS_SEASON_RANK_rolling_5', 'AWAY_EFG_PCT_rolling_5', 'AWAY_FTA_RATE_rolling_5', 'AWAY_TM_TOV_PCT_rolling_5', 'AWAY_OREB_PCT_rolling_5', 'AWAY_W_PCT_RANK_rolling_5', 'AWAY_PTS_rolling_5', 'AWAY_PTS_SEASON_RANK_rolling_5', 'HOME_EFG_PCT_rolling_15', 'HOME_FTA_RATE_rolling_15', 'HOME_TM_TOV_PCT_rolling_15', 'HOME_OREB_PCT_rolling_15', 'HOME_W_PCT_RANK_rolling_15', 'HOME_PTS_rolling_15', 'HOME_PTS_SEASON_RANK_rolling_15', 'AWAY_EFG_PCT_rolling_15', 'AWAY_FTA_RATE_rolling_15', 'AWAY_TM_TOV_PCT_rolling_15', 'AWAY_OREB_PCT_rolling_15', 'AWAY_W_PCT_RANK_rolling_15', 'AWAY_PTS_rolling_15', 'AWAY_PTS_SEASON_RANK_rolling_15', 'target']

In [27]:
predictors=[
      'HOME_EFG_PCT_rolling_15', 'HOME_FTA_RATE_rolling_15', 'HOME_TM_TOV_PCT_rolling_15', 'HOME_OREB_PCT_rolling_15', 'HOME_PTS_SEASON_RANK_rolling_15',
    'AWAY_EFG_PCT_rolling_15', 'AWAY_FTA_RATE_rolling_15', 'AWAY_TM_TOV_PCT_rolling_15', 'AWAY_OREB_PCT_rolling_15', 'AWAY_PTS_SEASON_RANK_rolling_15', 'HOME_is_home',
    'HOME_EFG_PCT_rolling_5', 'HOME_FTA_RATE_rolling_5', 'HOME_TM_TOV_PCT_rolling_5', 'HOME_OREB_PCT_rolling_5', 'HOME_PTS_SEASON_RANK_rolling_5',
    'AWAY_EFG_PCT_rolling_5', 'AWAY_FTA_RATE_rolling_5', 'AWAY_TM_TOV_PCT_rolling_5', 'AWAY_OREB_PCT_rolling_5', 'AWAY_PTS_SEASON_RANK_rolling_5'

]

In [28]:
'''
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

rolling_df[predictors + ["HOME_PTS"]] = scaler.fit_transform(rolling_df[predictors +["HOME_PTS"]])
'''

'\nfrom sklearn.preprocessing import MinMaxScaler\nscaler = MinMaxScaler()\n\nrolling_df[predictors + ["HOME_PTS"]] = scaler.fit_transform(rolling_df[predictors +["HOME_PTS"]])\n'

In [29]:
import matplotlib.pyplot as plt

from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

def train_test_model(data, predictors, model):
    train = data[(data["HOME_SEASON_YEAR"] < '2021-22') & (data["HOME_SEASON_YEAR"] >= '2000-01')]
    test = data[data["HOME_SEASON_YEAR"] == '2021-22']
    
    model.fit(train[predictors], train["target"])
    
    predictions = model.predict(test[predictors])
    
    combined = pd.DataFrame(dict(actual=test["target"], prediction=predictions))
    results = pd.crosstab(index=combined["actual"],columns=combined["prediction"])
    
    precision = precision_score(test["target"], predictions)
    recall = recall_score(test["target"], predictions, average='macro')
    f1Score = f1_score(test["target"], predictions, average='macro')
    
    scores = {'Precision: ':precision,'Recall: ':recall,'F1 score: ':f1Score}
    
    combined = combined.merge(data[["HOME_GAME_DATE","HOME_TEAM_NAME","AWAY_TEAM_NAME","HOME_WL"]], left_index=True, right_index=True)
    
    return combined, scores, results, model

def make_predictions(data, predictors, model):
    values = [data[predictors].values]
    
    prediction = model.predict(values)[0]
    
    prediction_df = data[["HOME_TEAM_NAME","HOME_MATCHUP"]] 
    if prediction == 0:
        prediction_df["Prediction"] = "L"
    else:
        prediction_df["Prediction"] = "W"
        
    predict_proba = model.predict_proba(values)[0]
    
    prediction_df["Win prob."] = predict_proba[1]
    prediction_df["Loss prob."] = predict_proba[0]
    
    
    return prediction_df

In [30]:
from sklearn.ensemble import GradientBoostingClassifier
gb = GradientBoostingClassifier()

combined, scores, results, model = train_test_model(rolling_df, predictors, gb)

In [31]:
scores

{'Precision: ': 0.5978674790555979,
 'Recall: ': 0.5993812838360402,
 'F1 score: ': 0.5993573197890353}

In [32]:
results

prediction    0    1
actual
0           765  528
1           508  785

# WOW

In [33]:
pd.set_option('display.max_rows', 10)

In [34]:
from nba_api.stats.endpoints import leaguedashteamstats

In [35]:
sixersPTS = leaguedashteamstats.LeagueDashTeamStats(team_id_nullable=1610612755, per_mode_detailed="PerGame").get_data_frames()[0] # sixers
sixers = leaguedashteamstats.LeagueDashTeamStats(team_id_nullable=1610612755, measure_type_detailed_defense="Four Factors").get_data_frames()[0] # sixers

In [36]:
sixers

,TEAM_ID,TEAM_NAME,GP,W,L,W_PCT,MIN,EFG_PCT,FTA_RATE,TM_TOV_PCT,...,EFG_PCT_RANK,FTA_RATE_RANK,TM_TOV_PCT_RANK,OREB_PCT_RANK,OPP_EFG_PCT_RANK,OPP_FTA_RATE_RANK,OPP_TOV_PCT_RANK,OPP_OREB_PCT_RANK,CFID,CFPARAMS
0,1610612755,Philadelphia 76ers,82,51,31,0.622,3961.0,0.534,0.282,0.129,...,1,1,1,1,1,1,1,1,10,Philadelphia 76ers

In [37]:
sixersPTS

,TEAM_ID,TEAM_NAME,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,...,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,CFID,CFPARAMS
0,1610612755,Philadelphia 76ers,82,51,31,0.622,48.3,39.4,84.5,0.466,...,1,1,1,1,1,1,1,1,10,Philadelphia 76ers

In [38]:
sixers = sixers.join(sixersPTS['PTS'])

In [39]:
sixers.columns

Index(['TEAM_ID', 'TEAM_NAME', 'GP', 'W', 'L', 'W_PCT', 'MIN', 'EFG_PCT',
       'FTA_RATE', 'TM_TOV_PCT', 'OREB_PCT', 'OPP_EFG_PCT', 'OPP_FTA_RATE',
       'OPP_TOV_PCT', 'OPP_OREB_PCT', 'GP_RANK', 'W_RANK', 'L_RANK',
       'W_PCT_RANK', 'MIN_RANK', 'EFG_PCT_RANK', 'FTA_RATE_RANK',
       'TM_TOV_PCT_RANK', 'OREB_PCT_RANK', 'OPP_EFG_PCT_RANK',
       'OPP_FTA_RATE_RANK', 'OPP_TOV_PCT_RANK', 'OPP_OREB_PCT_RANK', 'CFID',
       'CFPARAMS', 'PTS'],
      dtype='object')

In [40]:
rolling_df.columns

Index(['HOME_SEASON_YEAR', 'HOME_GAME_DATE', 'HOME_TEAM_NAME',
       'HOME_TEAM_ABBREVIATION', 'HOME_TEAM_ID', 'GAME_ID', 'HOME_WL',
       'HOME_EFG_PCT', 'HOME_FTA_RATE', 'HOME_TM_TOV_PCT', 'HOME_OREB_PCT',
       'HOME_W_PCT_RANK', 'HOME_PTS', 'HOME_is_home', 'HOME_PTS_SEASON_RANK',
       'AWAY_SEASON_YEAR', 'AWAY_GAME_DATE', 'AWAY_TEAM_NAME',
       'AWAY_TEAM_ABBREVIATION', 'AWAY_TEAM_ID', 'AWAY_WL', 'AWAY_EFG_PCT',
       'AWAY_FTA_RATE', 'AWAY_TM_TOV_PCT', 'AWAY_OREB_PCT', 'AWAY_W_PCT_RANK',
       'AWAY_PTS', 'AWAY_is_home', 'AWAY_PTS_SEASON_RANK',
       'HOME_EFG_PCT_rolling_5', 'HOME_FTA_RATE_rolling_5',
       'HOME_TM_TOV_PCT_rolling_5', 'HOME_OREB_PCT_rolling_5',
       'HOME_W_PCT_RANK_rolling_5', 'HOME_PTS_rolling_5',
       'HOME_PTS_SEASON_RANK_rolling_5', 'AWAY_EFG_PCT_rolling_5',
       'AWAY_FTA_RATE_rolling_5', 'AWAY_TM_TOV_PCT_rolling_5',
       'AWAY_OREB_PCT_rolling_5', 'AWAY_W_PCT_RANK_rolling_5',
       'AWAY_PTS_rolling_5', 'AWAY_PTS_SEASON_RANK_rolling_5',
       'HOME_EFG_PCT_rolling_15', 'HOME_FTA_RATE_rolling_15',
       'HOME_TM_TOV_PCT_rolling_15', 'HOME_OREB_PCT_rolling_15',
       'HOME_W_PCT_RANK_rolling_15', 'HOME_PTS_rolling_15',
       'HOME_PTS_SEASON_RANK_rolling_15', 'AWAY_EFG_PCT_rolling_15',
       'AWAY_FTA_RATE_rolling_15', 'AWAY_TM_TOV_PCT_rolling_15',
       'AWAY_OREB_PCT_rolling_15', 'AWAY_W_PCT_RANK_rolling_15',
       'AWAY_PTS_rolling_15', 'AWAY_PTS_SEASON_RANK_rolling_15', 'target'],
      dtype='object')

In [41]:
sixers = sixers[['TEAM_ID', 'TEAM_NAME',  'EFG_PCT',
       'FTA_RATE', 'TM_TOV_PCT', 'OREB_PCT', 'W_PCT_RANK' ,'PTS']]
sixers = sixers.add_prefix('HOME_').reset_index()

In [42]:
sixers.columns

Index(['index', 'HOME_TEAM_ID', 'HOME_TEAM_NAME', 'HOME_EFG_PCT',
       'HOME_FTA_RATE', 'HOME_TM_TOV_PCT', 'HOME_OREB_PCT', 'HOME_W_PCT_RANK',
       'HOME_PTS'],
      dtype='object')

In [43]:
sixers_opp_pts = leaguedashteamstats.LeagueDashTeamStats(team_id_nullable=1610612748,   per_mode_detailed="PerGame").get_data_frames()[0] # sixers
sixers_opp = leaguedashteamstats.LeagueDashTeamStats(team_id_nullable=1610612755, measure_type_detailed_defense="Four Factors").get_data_frames()[0] # sixers

sixers_opp = sixers_opp.join(sixers_opp_pts['PTS'])

In [44]:
sixers_opp = sixers_opp[['TEAM_ID', 'TEAM_NAME',  'EFG_PCT',
       'FTA_RATE', 'TM_TOV_PCT', 'OREB_PCT', 'W_PCT_RANK' ,'PTS']]
sixers_opp = sixers_opp.add_prefix('AWAY_').reset_index()

In [45]:
sixers_opp.columns

Index(['index', 'AWAY_TEAM_ID', 'AWAY_TEAM_NAME', 'AWAY_EFG_PCT',
       'AWAY_FTA_RATE', 'AWAY_TM_TOV_PCT', 'AWAY_OREB_PCT', 'AWAY_W_PCT_RANK',
       'AWAY_PTS'],
      dtype='object')

In [46]:
sixers = sixers.merge(sixers_opp, on ='index')

In [47]:
sixers

,index,HOME_TEAM_ID,HOME_TEAM_NAME,HOME_EFG_PCT,HOME_FTA_RATE,HOME_TM_TOV_PCT,HOME_OREB_PCT,HOME_W_PCT_RANK,HOME_PTS,AWAY_TEAM_ID,AWAY_TEAM_NAME,AWAY_EFG_PCT,AWAY_FTA_RATE,AWAY_TM_TOV_PCT,AWAY_OREB_PCT,AWAY_W_PCT_RANK,AWAY_PTS
0,0,1610612755,Philadelphia 76ers,0.534,0.282,0.129,0.246,1,109.9,1610612755,Philadelphia 76ers,0.534,0.282,0.129,0.246,1,110.0

In [48]:
sixers_stats = combined_df[combined_df['HOME_TEAM_ID'] == 1610612755]
sixers_stats = sixers_stats.sort_values(by="HOME_GAME_DATE")

In [49]:
sixers_stats

,HOME_SEASON_YEAR,HOME_GAME_DATE,HOME_TEAM_NAME,HOME_TEAM_ABBREVIATION,HOME_TEAM_ID,GAME_ID,HOME_WL,HOME_EFG_PCT,HOME_FTA_RATE,HOME_TM_TOV_PCT,...,AWAY_TEAM_ID,AWAY_WL,AWAY_EFG_PCT,AWAY_FTA_RATE,AWAY_TM_TOV_PCT,AWAY_OREB_PCT,AWAY_W_PCT_RANK,AWAY_PTS,AWAY_is_home,AWAY_PTS_SEASON_RANK
1178,2000-01,2000-10-31T00:00:00,Philadelphia 76ers,PHI,1610612755,20000001,W,0.598,0.455,0.159,...,1610612752,L,0.379,0.343,0.250,0.354,1190,72,1,2470.5
1173,2000-01,2000-11-01T00:00:00,Philadelphia 76ers,PHI,1610612755,20000015,W,0.500,0.329,0.152,...,1610612761,L,0.483,0.209,0.174,0.426,1190,98,0,992.5
1160,2000-01,2000-11-03T00:00:00,Philadelphia 76ers,PHI,1610612755,20000030,W,0.386,0.380,0.262,...,1610612753,L,0.366,0.349,0.192,0.290,1190,80,1,2269.0
1152,2000-01,2000-11-04T00:00:00,Philadelphia 76ers,PHI,1610612755,20000035,W,0.418,0.452,0.115,...,1610612748,L,0.493,0.160,0.195,0.295,1190,82,1,2170.0
1121,2000-01,2000-11-08T00:00:00,Philadelphia 76ers,PHI,1610612755,20000062,W,0.500,0.427,0.190,...,1610612765,L,0.433,0.225,0.224,0.415,1190,94,0,1325.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28084,2021-22,2022-05-02T00:00:00,Philadelphia 76ers,PHI,1610612755,42100201,L,0.468,0.253,0.160,...,1610612748,W,0.484,0.196,0.140,0.396,1,106,1,1635.0
28080,2021-22,2022-05-04T00:00:00,Philadelphia 76ers,PHI,1610612755,42100202,L,0.500,0.262,0.105,...,1610612748,W,0.603,0.397,0.147,0.286,1,119,1,626.0
28078,2021-22,2022-05-06T00:00:00,Philadelphia 76ers,PHI,1610612755,42100203,W,0.597,0.328,0.213,...,1610612748,L,0.396,0.312,0.148,0.269,64,79,0,2575.5
28075,2021-22,2022-05-08T00:00:00,Philadelphia 76ers,PHI,1610612755,42100204,W,0.662,0.500,0.177,...,1610612748,L,0.506,0.341,0.133,0.289,64,108,0,1486.5
28070,2021-22,2022-05-10T00:00:00,Philadelphia 76ers,PHI,1610612755,42100205,L,0.418,0.176,0.174,...,1610612748,W,0.613,0.274,0.118,0.318,1,120,1,567.0

In [50]:
sixers_stats["target"] = (sixers_stats["HOME_WL"] == "W").astype("int") # count draw and loss as not a win

In [51]:
sixers_stats

,HOME_SEASON_YEAR,HOME_GAME_DATE,HOME_TEAM_NAME,HOME_TEAM_ABBREVIATION,HOME_TEAM_ID,GAME_ID,HOME_WL,HOME_EFG_PCT,HOME_FTA_RATE,HOME_TM_TOV_PCT,...,AWAY_WL,AWAY_EFG_PCT,AWAY_FTA_RATE,AWAY_TM_TOV_PCT,AWAY_OREB_PCT,AWAY_W_PCT_RANK,AWAY_PTS,AWAY_is_home,AWAY_PTS_SEASON_RANK,target
1178,2000-01,2000-10-31T00:00:00,Philadelphia 76ers,PHI,1610612755,20000001,W,0.598,0.455,0.159,...,L,0.379,0.343,0.250,0.354,1190,72,1,2470.5,1
1173,2000-01,2000-11-01T00:00:00,Philadelphia 76ers,PHI,1610612755,20000015,W,0.500,0.329,0.152,...,L,0.483,0.209,0.174,0.426,1190,98,0,992.5,1
1160,2000-01,2000-11-03T00:00:00,Philadelphia 76ers,PHI,1610612755,20000030,W,0.386,0.380,0.262,...,L,0.366,0.349,0.192,0.290,1190,80,1,2269.0,1
1152,2000-01,2000-11-04T00:00:00,Philadelphia 76ers,PHI,1610612755,20000035,W,0.418,0.452,0.115,...,L,0.493,0.160,0.195,0.295,1190,82,1,2170.0,1
1121,2000-01,2000-11-08T00:00:00,Philadelphia 76ers,PHI,1610612755,20000062,W,0.500,0.427,0.190,...,L,0.433,0.225,0.224,0.415,1190,94,0,1325.5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28084,2021-22,2022-05-02T00:00:00,Philadelphia 76ers,PHI,1610612755,42100201,L,0.468,0.253,0.160,...,W,0.484,0.196,0.140,0.396,1,106,1,1635.0,0
28080,2021-22,2022-05-04T00:00:00,Philadelphia 76ers,PHI,1610612755,42100202,L,0.500,0.262,0.105,...,W,0.603,0.397,0.147,0.286,1,119,1,626.0,0
28078,2021-22,2022-05-06T00:00:00,Philadelphia 76ers,PHI,1610612755,42100203,W,0.597,0.328,0.213,...,L,0.396,0.312,0.148,0.269,64,79,0,2575.5,1
28075,2021-22,2022-05-08T00:00:00,Philadelphia 76ers,PHI,1610612755,42100204,W,0.662,0.500,0.177,...,L,0.506,0.341,0.133,0.289,64,108,0,1486.5,1
28070,2021-22,2022-05-10T00:00:00,Philadelphia 76ers,PHI,1610612755,42100205,L,0.418,0.176,0.174,...,W,0.613,0.274,0.118,0.318,1,120,1,567.0,0

In [52]:
sixers.columns

Index(['index', 'HOME_TEAM_ID', 'HOME_TEAM_NAME', 'HOME_EFG_PCT',
       'HOME_FTA_RATE', 'HOME_TM_TOV_PCT', 'HOME_OREB_PCT', 'HOME_W_PCT_RANK',
       'HOME_PTS', 'AWAY_TEAM_ID', 'AWAY_TEAM_NAME', 'AWAY_EFG_PCT',
       'AWAY_FTA_RATE', 'AWAY_TM_TOV_PCT', 'AWAY_OREB_PCT', 'AWAY_W_PCT_RANK',
       'AWAY_PTS'],
      dtype='object')

In [53]:
sixers_stats.columns

Index(['HOME_SEASON_YEAR', 'HOME_GAME_DATE', 'HOME_TEAM_NAME',
       'HOME_TEAM_ABBREVIATION', 'HOME_TEAM_ID', 'GAME_ID', 'HOME_WL',
       'HOME_EFG_PCT', 'HOME_FTA_RATE', 'HOME_TM_TOV_PCT', 'HOME_OREB_PCT',
       'HOME_W_PCT_RANK', 'HOME_PTS', 'HOME_is_home', 'HOME_PTS_SEASON_RANK',
       'AWAY_SEASON_YEAR', 'AWAY_GAME_DATE', 'AWAY_TEAM_NAME',
       'AWAY_TEAM_ABBREVIATION', 'AWAY_TEAM_ID', 'AWAY_WL', 'AWAY_EFG_PCT',
       'AWAY_FTA_RATE', 'AWAY_TM_TOV_PCT', 'AWAY_OREB_PCT', 'AWAY_W_PCT_RANK',
       'AWAY_PTS', 'AWAY_is_home', 'AWAY_PTS_SEASON_RANK', 'target'],
      dtype='object')

In [54]:
sixers["HOME_is_home"] = 1
sixers["AWAY_is_home"] = 0

In [55]:
sixers.columns

Index(['index', 'HOME_TEAM_ID', 'HOME_TEAM_NAME', 'HOME_EFG_PCT',
       'HOME_FTA_RATE', 'HOME_TM_TOV_PCT', 'HOME_OREB_PCT', 'HOME_W_PCT_RANK',
       'HOME_PTS', 'AWAY_TEAM_ID', 'AWAY_TEAM_NAME', 'AWAY_EFG_PCT',
       'AWAY_FTA_RATE', 'AWAY_TM_TOV_PCT', 'AWAY_OREB_PCT', 'AWAY_W_PCT_RANK',
       'AWAY_PTS', 'HOME_is_home', 'AWAY_is_home'],
      dtype='object')

In [56]:
sixers["target"] = 0
sixers["HOME_TEAM_NAME"] = "Philadelphia 76ers"
sixers["HOME_MATCHUP"] = "Philadelphia 76ers @ Miami Heat"
sixers["HOME_SEASON_YEAR"] = "2021-22"
sixers["HOME_PTS_SEASON_RANK"] = 0

In [57]:
input_data = sixers_stats.append(sixers)

In [58]:
input_data # last row can now be input data

,HOME_SEASON_YEAR,HOME_GAME_DATE,HOME_TEAM_NAME,HOME_TEAM_ABBREVIATION,HOME_TEAM_ID,GAME_ID,HOME_WL,HOME_EFG_PCT,HOME_FTA_RATE,HOME_TM_TOV_PCT,...,AWAY_FTA_RATE,AWAY_TM_TOV_PCT,AWAY_OREB_PCT,AWAY_W_PCT_RANK,AWAY_PTS,AWAY_is_home,AWAY_PTS_SEASON_RANK,target,index,HOME_MATCHUP
1178,2000-01,2000-10-31T00:00:00,Philadelphia 76ers,PHI,1610612755,20000001.0,W,0.598,0.455,0.159,...,0.343,0.250,0.354,1190,72.0,1,2470.5,1,NaN,NaN
1173,2000-01,2000-11-01T00:00:00,Philadelphia 76ers,PHI,1610612755,20000015.0,W,0.500,0.329,0.152,...,0.209,0.174,0.426,1190,98.0,0,992.5,1,NaN,NaN
1160,2000-01,2000-11-03T00:00:00,Philadelphia 76ers,PHI,1610612755,20000030.0,W,0.386,0.380,0.262,...,0.349,0.192,0.290,1190,80.0,1,2269.0,1,NaN,NaN
1152,2000-01,2000-11-04T00:00:00,Philadelphia 76ers,PHI,1610612755,20000035.0,W,0.418,0.452,0.115,...,0.160,0.195,0.295,1190,82.0,1,2170.0,1,NaN,NaN
1121,2000-01,2000-11-08T00:00:00,Philadelphia 76ers,PHI,1610612755,20000062.0,W,0.500,0.427,0.190,...,0.225,0.224,0.415,1190,94.0,0,1325.5,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28080,2021-22,2022-05-04T00:00:00,Philadelphia 76ers,PHI,1610612755,42100202.0,L,0.500,0.262,0.105,...,0.397,0.147,0.286,1,119.0,1,626.0,0,NaN,NaN
28078,2021-22,2022-05-06T00:00:00,Philadelphia 76ers,PHI,1610612755,42100203.0,W,0.597,0.328,0.213,...,0.312,0.148,0.269,64,79.0,0,2575.5,1,NaN,NaN
28075,2021-22,2022-05-08T00:00:00,Philadelphia 76ers,PHI,1610612755,42100204.0,W,0.662,0.500,0.177,...,0.341,0.133,0.289,64,108.0,0,1486.5,1,NaN,NaN
28070,2021-22,2022-05-10T00:00:00,Philadelphia 76ers,PHI,1610612755,42100205.0,L,0.418,0.176,0.174,...,0.274,0.118,0.318,1,120.0,1,567.0,0,NaN,NaN
0,2021-22,NaN,Philadelphia 76ers,NaN,1610612755,NaN,NaN,0.534,0.282,0.129,...,0.282,0.129,0.246,1,110.0,0,NaN,0,0.0,Philadelphia 76ers @ Miami Heat

In [59]:
input_data.columns

Index(['HOME_SEASON_YEAR', 'HOME_GAME_DATE', 'HOME_TEAM_NAME',
       'HOME_TEAM_ABBREVIATION', 'HOME_TEAM_ID', 'GAME_ID', 'HOME_WL',
       'HOME_EFG_PCT', 'HOME_FTA_RATE', 'HOME_TM_TOV_PCT', 'HOME_OREB_PCT',
       'HOME_W_PCT_RANK', 'HOME_PTS', 'HOME_is_home', 'HOME_PTS_SEASON_RANK',
       'AWAY_SEASON_YEAR', 'AWAY_GAME_DATE', 'AWAY_TEAM_NAME',
       'AWAY_TEAM_ABBREVIATION', 'AWAY_TEAM_ID', 'AWAY_WL', 'AWAY_EFG_PCT',
       'AWAY_FTA_RATE', 'AWAY_TM_TOV_PCT', 'AWAY_OREB_PCT', 'AWAY_W_PCT_RANK',
       'AWAY_PTS', 'AWAY_is_home', 'AWAY_PTS_SEASON_RANK', 'target', 'index',
       'HOME_MATCHUP'],
      dtype='object')

In [60]:
cols = ['HOME_EFG_PCT', 'HOME_FTA_RATE',
       'HOME_TM_TOV_PCT', 'HOME_OREB_PCT', 'HOME_W_PCT_RANK', 'HOME_PTS','HOME_PTS_SEASON_RANK','AWAY_EFG_PCT', 'AWAY_FTA_RATE',
       'AWAY_TM_TOV_PCT', 'AWAY_OREB_PCT', 'AWAY_W_PCT_RANK', 'AWAY_PTS','AWAY_PTS_SEASON_RANK']
new_cols = [f"{c}_rolling_5" for c in cols]

input_data_rolling = input_data.groupby("HOME_TEAM_ID").apply(lambda x: rolling_averages(x, cols, new_cols, 3))
input_data_rolling = input_data_rolling.droplevel('HOME_TEAM_ID').reset_index().drop('index', axis=1)

In [61]:
cols = ['HOME_EFG_PCT', 'HOME_FTA_RATE',
       'HOME_TM_TOV_PCT', 'HOME_OREB_PCT', 'HOME_W_PCT_RANK', 'HOME_PTS','HOME_PTS_SEASON_RANK','AWAY_EFG_PCT', 'AWAY_FTA_RATE',
       'AWAY_TM_TOV_PCT', 'AWAY_OREB_PCT', 'AWAY_W_PCT_RANK', 'AWAY_PTS','AWAY_PTS_SEASON_RANK']
new_cols = [f"{c}_rolling_15" for c in cols]

input_data_rolling= input_data_rolling.groupby("HOME_TEAM_ID").apply(lambda x: rolling_averages(x, cols, new_cols, 15))
input_data_rolling = input_data_rolling.droplevel('HOME_TEAM_ID').reset_index().drop('index', axis=1)

input_data = input_data_rolling

In [62]:
columns = input_data.columns.to_list()

In [63]:
predictors

['HOME_EFG_PCT_rolling_15',
 'HOME_FTA_RATE_rolling_15',
 'HOME_TM_TOV_PCT_rolling_15',
 'HOME_OREB_PCT_rolling_15',
 'HOME_PTS_SEASON_RANK_rolling_15',
 'AWAY_EFG_PCT_rolling_15',
 'AWAY_FTA_RATE_rolling_15',
 'AWAY_TM_TOV_PCT_rolling_15',
 'AWAY_OREB_PCT_rolling_15',
 'AWAY_PTS_SEASON_RANK_rolling_15',
 'HOME_is_home',
 'HOME_EFG_PCT_rolling_5',
 'HOME_FTA_RATE_rolling_5',
 'HOME_TM_TOV_PCT_rolling_5',
 'HOME_OREB_PCT_rolling_5',
 'HOME_PTS_SEASON_RANK_rolling_5',
 'AWAY_EFG_PCT_rolling_5',
 'AWAY_FTA_RATE_rolling_5',
 'AWAY_TM_TOV_PCT_rolling_5',
 'AWAY_OREB_PCT_rolling_5',
 'AWAY_PTS_SEASON_RANK_rolling_5']

In [64]:
for item in predictors:
    if item in columns:
        pass
    else:
       # do something
       print(item)

In [65]:
input_data = input_data.iloc[-1]

In [66]:
input_data

level_0                                             0
HOME_SEASON_YEAR                              2021-22
HOME_GAME_DATE                                    NaN
HOME_TEAM_NAME                     Philadelphia 76ers
HOME_TEAM_ABBREVIATION                            NaN
                                          ...
AWAY_TM_TOV_PCT_rolling_15                     0.1312
AWAY_OREB_PCT_rolling_15                     0.298333
AWAY_W_PCT_RANK_rolling_15                      272.2
AWAY_PTS_rolling_15                           107.867
AWAY_PTS_SEASON_RANK_rolling_15               1400.53
Name: 1875, Length: 60, dtype: object

In [67]:
prediction_df = make_predictions(input_data, predictors, gb)

In [68]:
prediction_df

HOME_TEAM_NAME                 Philadelphia 76ers
HOME_MATCHUP      Philadelphia 76ers @ Miami Heat
Prediction                                      W
Win prob.                                0.624231
Loss prob.                               0.375769
Name: 1875, dtype: object

In [69]:
gb.feature_importances_

array([0.07521379, 0.01180212, 0.01520414, 0.00203788, 0.19389844,
       0.05323804, 0.0079767 , 0.00499653, 0.00699263, 0.20332044,
       0.35364462, 0.00597399, 0.0020952 , 0.00689737, 0.00957048,
       0.01516178, 0.00291968, 0.00651795, 0.00860577, 0.00706381,
       0.00686864])

In [70]:
feature_importance = pd.DataFrame([gb.feature_importances_], columns=predictors)

In [71]:
feature_importance # we see that the model mostly predicts that the winning team is the one with the higher record

,HOME_EFG_PCT_rolling_15,HOME_FTA_RATE_rolling_15,HOME_TM_TOV_PCT_rolling_15,HOME_OREB_PCT_rolling_15,HOME_PTS_SEASON_RANK_rolling_15,AWAY_EFG_PCT_rolling_15,AWAY_FTA_RATE_rolling_15,AWAY_TM_TOV_PCT_rolling_15,AWAY_OREB_PCT_rolling_15,AWAY_PTS_SEASON_RANK_rolling_15,...,HOME_EFG_PCT_rolling_5,HOME_FTA_RATE_rolling_5,HOME_TM_TOV_PCT_rolling_5,HOME_OREB_PCT_rolling_5,HOME_PTS_SEASON_RANK_rolling_5,AWAY_EFG_PCT_rolling_5,AWAY_FTA_RATE_rolling_5,AWAY_TM_TOV_PCT_rolling_5,AWAY_OREB_PCT_rolling_5,AWAY_PTS_SEASON_RANK_rolling_5
0,0.075214,0.011802,0.015204,0.002038,0.193898,0.053238,0.007977,0.004997,0.006993,0.20332,...,0.005974,0.002095,0.006897,0.00957,0.015162,0.00292,0.006518,0.008606,0.007064,0.006869

In [72]:
# how well would a model that predicts higher win rank as a win

win_rank = rolling_df

win_rank['WIN'] = 0

win_rank['WIN'].where(win_rank['HOME_W_PCT_RANK_rolling_15'] > win_rank['AWAY_W_PCT_RANK_rolling_15'], 1, inplace=True)

    
print(precision_score(win_rank["target"], win_rank["WIN"]))

0.5828654605947182

In [73]:
list = df['W_PCT_RANK'].to_list()

In [74]:
df

,Unnamed: 0,SEASON_YEAR,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,...,EFG_PCT_RANK,FTA_RATE_RANK,TM_TOV_PCT_RANK,OREB_PCT_RANK,OPP_EFG_PCT_RANK,OPP_FTA_RATE_RANK,OPP_TOV_PCT_RANK,OPP_OREB_PCT_RANK,PTS,PTS_SEASON_RANK
0,0,2000-01,1610612744,GSW,Golden State Warriors,20001188,2001-04-18T00:00:00,GSW vs. VAN,L,48.0,...,2369,1627,1427,1,518,546,1225,2341,81,2221.5
1,1,2000-01,1610612755,PHI,Philadelphia 76ers,20001181,2001-04-18T00:00:00,PHI vs. CHI,L,48.0,...,1457,1715,2052,378,1856,1707,1870,47,86,1931.5
2,2,2000-01,1610612754,IND,Indiana Pacers,20001184,2001-04-18T00:00:00,IND @ CLE,W,53.0,...,839,2056,1448,1875,327,729,2269,812,105,466.0
3,3,2000-01,1610612766,CHH,Charlotte Hornets,20001179,2001-04-18T00:00:00,CHH @ BOS,W,48.0,...,1734,834,1246,277,761,1282,1588,834,97,1076.5
4,4,2000-01,1610612753,ORL,Orlando Magic,20001183,2001-04-18T00:00:00,ORL vs. MIA,L,48.0,...,883,1807,1846,1426,1530,774,1339,2257,91,1566.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56257,56257,2021-22,1610612742,DAL,Dallas Mavericks,42100171,2022-04-16T00:00:00,DAL vs. UTA,L,48.0,...,115,8,4,111,30,72,49,118,93,2370.5
56258,56258,2021-22,1610612761,TOR,Toronto Raptors,42100131,2022-04-16T00:00:00,TOR @ PHI,L,48.0,...,47,53,7,62,110,113,125,81,111,1233.0
56259,56259,2021-22,1610612755,PHI,Philadelphia 76ers,42100131,2022-04-16T00:00:00,PHI vs. TOR,W,48.0,...,17,14,2,46,79,74,120,65,131,152.0
56260,56260,2021-22,1610612750,MIN,Minnesota Timberwolves,42100151,2022-04-16T00:00:00,MIN @ MEM,W,48.0,...,27,44,103,32,38,123,96,51,130,176.5
56261,56261,2021-22,1610612743,DEN,Denver Nuggets,42100161,2022-04-16T00:00:00,DEN @ GSW,L,48.0,...,72,122,36,24,113,96,72,106,107,1562.0

In [75]:
combined_df

,HOME_SEASON_YEAR,HOME_GAME_DATE,HOME_TEAM_NAME,HOME_TEAM_ABBREVIATION,HOME_TEAM_ID,GAME_ID,HOME_WL,HOME_EFG_PCT,HOME_FTA_RATE,HOME_TM_TOV_PCT,...,AWAY_TEAM_ID,AWAY_WL,AWAY_EFG_PCT,AWAY_FTA_RATE,AWAY_TM_TOV_PCT,AWAY_OREB_PCT,AWAY_W_PCT_RANK,AWAY_PTS,AWAY_is_home,AWAY_PTS_SEASON_RANK
0,2000-01,2001-04-18T00:00:00,Golden State Warriors,GSW,1610612744,20001188,L,0.319,0.255,0.169,...,1610612763,W,0.424,0.228,0.157,0.466,1,95,0,1242.0
1,2000-01,2001-04-18T00:00:00,Philadelphia 76ers,PHI,1610612755,20001181,L,0.455,0.244,0.207,...,1610612741,W,0.522,0.368,0.128,0.167,1,92,0,1483.0
2,2000-01,2001-04-18T00:00:00,Indiana Pacers,IND,1610612754,20001184,W,0.495,0.196,0.170,...,1610612739,L,0.404,0.253,0.094,0.279,1190,101,1,743.0
3,2000-01,2001-04-18T00:00:00,Charlotte Hornets,CHH,1610612766,20001179,W,0.435,0.345,0.161,...,1610612738,L,0.444,0.313,0.141,0.280,1190,92,1,1483.0
4,2000-01,2001-04-18T00:00:00,Orlando Magic,ORL,1610612753,20001183,L,0.494,0.231,0.191,...,1610612748,W,0.494,0.258,0.152,0.429,1,103,0,600.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28126,2021-22,2022-04-17T00:00:00,Miami Heat,MIA,1610612748,42100101,W,0.634,0.220,0.155,...,1610612737,L,0.453,0.360,0.186,0.204,64,91,0,2431.5
28127,2021-22,2022-04-16T00:00:00,Dallas Mavericks,DAL,1610612742,42100171,L,0.441,0.447,0.078,...,1610612762,W,0.476,0.277,0.154,0.396,1,99,0,2099.5
28128,2021-22,2022-04-16T00:00:00,Denver Nuggets,DEN,1610612743,42100161,L,0.522,0.140,0.117,...,1610612744,W,0.622,0.354,0.138,0.341,1,123,1,413.5
28129,2021-22,2022-04-16T00:00:00,Minnesota Timberwolves,MIN,1610612750,42100151,W,0.589,0.300,0.178,...,1610612763,L,0.494,0.500,0.114,0.250,64,117,1,760.5
28130,2021-22,2022-04-16T00:00:00,Philadelphia 76ers,PHI,1610612755,42100131,W,0.607,0.405,0.045,...,1610612761,L,0.561,0.280,0.088,0.279,64,111,0,1233.0

In [76]:
copy_df = rolling_df

In [77]:
copy_df[['HOME_TEAM_ID','AWAY_TEAM_ID','GAME_ID']]

       HOME_TEAM_ID  AWAY_TEAM_ID   GAME_ID
0        1610612737    1610612748  20000277
1        1610612737    1610612739  20000285
2        1610612737    1610612758  20000305
3        1610612737    1610612765  20000315
4        1610612737    1610612741  20000331
...             ...           ...       ...
55717    1610612766    1610612755  22101161
55718    1610612766    1610612748  22101181
55719    1610612766    1610612753  22101196
55720    1610612766    1610612741  22101208
55721    1610612766    1610612764  22101217

[55722 rows x 3 columns]

In [80]:
def giveELO(df):
    
    df["ELO_rating"] = 1500 # GIVE STARING ELO TO FIRST CASE
    
    
    # FIND PREVIOUS GAME WITH TEAM ID AND GET THE ELO SCORE
        # REPEAT FOR OPPONENT
        
    # DO A CALCULATION
    
    # UPDATE NEW ELO AT CURRENT ROW
    
    # REPEAT
    return df
    
    
def calculateELO(df):
    game_ids = df['GAME_ID'].to_list()
    home_id = df['HOME_TEAM_ID'].unique()
    away_id = df['AWAY_TEAM_ID'].unique()

In [88]:
copy_df = giveELO(copy_df)
test = calculateELO(copy_df)

In [89]:
test

In [96]:
def getLastGamePlayed(df, GAME_ID, HOME_TEAM_ID):

    game = df[(df['GAME_ID'] == GAME_ID) & (df['HOME_TEAM_ID'] == HOME_TEAM_ID)]
    AWAY_TEAM_ID = df['AWAY_TEAM_ID'][(df['GAME_ID'] == GAME_ID) & (df['HOME_TEAM_ID'] == HOME_TEAM_ID)]
    
    gamesPlayed = df[df["HOME_TEAM_ID"] == HOME_TEAM_ID].reset_index()
    idx = gamesPlayed.index[gamesPlayed['GAME_ID'] == GAME_ID]
    HomeLastGamePlayed = gamesPlayed.iloc[idx-1]
    
    gamesPlayed = df[df["AWAY_TEAM_ID"] == AWAY_TEAM_ID].reset_index()
    idx = gamesPlayed.index[gamesPlayed['GAME_ID'] == GAME_ID]
    AwayLastGamePlayed = gamesPlayed.iloc[idx-1]
    
    
    return HomeLastGamePlayed, AwayLastGamePlayed

In [97]:
HomeLastGamePlayed, AwayLastGamePlayed = getLastGamePlayed(copy_df, 22101217, 1610612766)

ValueError: Can only compare identically-labeled Series objects

In [85]:
HomeLastGamePlayed[['HOME_TEAM_NAME','AWAY_TEAM_NAME']]

NameError: name 'HomeLastGamePlayed' is not defined

In [86]:
AwayLastGamePlayed[['HOME_TEAM_NAME','AWAY_TEAM_NAME']]

NameError: name 'AwayLastGamePlayed' is not defined