# Getting the data

In [1]:
import pandas as pd

In [2]:
from nba_api.stats.endpoints import teamgamelogs

In [3]:
df = teamgamelogs.TeamGameLogs(season_nullable="1999-00").get_data_frames()[0]

In [4]:
df

,SEASON_YEAR,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK
0,1999-00,1610612764,WAS,Washington Wizards,0029901182,2000-04-19T00:00:00,WAS @ MIL,L,48.0,39,...,927,626,261,2077,1656,1432,2139,1566,587,1461
1,1999-00,1610612766,CHH,Charlotte Hornets,0029901179,2000-04-19T00:00:00,CHH vs. MIA,W,48.0,31,...,2253,497,261,1574,1989,34,5,1011,2102,494
2,1999-00,1610612744,GSW,Golden State Warriors,0029901187,2000-04-19T00:00:00,GSW vs. PHX,L,48.0,32,...,1755,626,1238,111,948,1081,237,1011,1845,1886
3,1999-00,1610612747,LAL,Los Angeles Lakers,0029901185,2000-04-19T00:00:00,LAL @ SAS,L,53.0,41,...,32,941,261,2077,1656,724,867,1011,1113,1461
4,1999-00,1610612763,VAN,Vancouver Grizzlies,0029901184,2000-04-19T00:00:00,VAN @ HOU,W,48.0,35,...,1068,1654,814,944,1299,1724,93,2118,1232,919
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2373,1999-00,1610612739,CLE,Cleveland Cavaliers,0029900001,1999-11-02T00:00:00,CLE @ NYK,L,48.0,30,...,1755,941,1839,467,1989,2198,1811,1011,2062,1676
2374,1999-00,1610612761,TOR,Toronto Raptors,0029900006,1999-11-02T00:00:00,TOR vs. BOS,L,48.0,33,...,1990,1130,1456,668,447,724,515,1011,1704,1979
2375,1999-00,1610612762,UTA,Utah Jazz,0029900011,1999-11-02T00:00:00,UTA vs. LAL,L,48.0,29,...,1755,1494,1655,1240,656,1432,1638,284,2062,1607
2376,1999-00,1610612738,BOS,Boston Celtics,0029900006,1999-11-02T00:00:00,BOS @ TOR,W,48.0,38,...,1627,1298,1655,186,1299,1724,2139,1011,708,354
2377,1999-00,1610612755,PHI,Philadelphia 76ers,0029900009,1999-11-02T00:00:00,PHI @ SAS,L,48.0,30,...,2088,2168,616,467,948,2315,1089,135,2303,1979

In [5]:
season_list = []
for i in range((9)):
    season = "199" + str(i) + "-9" + str(i+1)
    season_list.append(season)
    
season_list.append("1999-00")

for i in range((9)):
    season = "200" + str(i) + "-0" + str(i+1)
    season_list.append(season)
    
season_list.append("2009-10")

for i in range((9)):
    season = "201" + str(i) + "-1" + str(i+1)
    season_list.append(season)
    
season_list.append("2019-20")
season_list.append("2020-21")
season_list.append("2021-22")

In [6]:
season_list

['1990-91',
 '1991-92',
 '1992-93',
 '1993-94',
 '1994-95',
 '1995-96',
 '1996-97',
 '1997-98',
 '1998-99',
 '1999-00',
 '2000-01',
 '2001-02',
 '2002-03',
 '2003-04',
 '2004-05',
 '2005-06',
 '2006-07',
 '2007-08',
 '2008-09',
 '2009-10',
 '2010-11',
 '2011-12',
 '2012-13',
 '2013-14',
 '2014-15',
 '2015-16',
 '2016-17',
 '2017-18',
 '2018-19',
 '2019-20',
 '2020-21',
 '2021-22']

In [7]:
import time

def getData(season_list):
    df = teamgamelogs.TeamGameLogs(season_nullable=season_list[0]).get_data_frames()[0]
    playoff_df = teamgamelogs.TeamGameLogs(season_nullable=season_list[0], season_type_nullable="Playoffs").get_data_frames()[0]
    df.append(playoff_df)
    print(f"{season_list[0]} is done")
    for i in range(len(season_list)-1):
        df_temp = teamgamelogs.TeamGameLogs(season_nullable=season_list[i+1]).get_data_frames()[0]
        playoff_df = teamgamelogs.TeamGameLogs(season_nullable=season_list[i+1], season_type_nullable="Playoffs").get_data_frames()[0]
        df = df.append(df_temp)
        df = df.append(playoff_df)
        print(f"{season_list[i+1]} is done")
        
        time.sleep(1)
        
    return df

In [8]:
df = getData(season_list)
df.to_csv("TrainingData.csv")

1990-91 is done
1991-92 is done
1992-93 is done
1993-94 is done
1994-95 is done
1995-96 is done
1996-97 is done
1997-98 is done
1998-99 is done
1999-00 is done
2000-01 is done
2001-02 is done
2002-03 is done
2003-04 is done
2004-05 is done
2005-06 is done
2006-07 is done
2007-08 is done
2008-09 is done
2009-10 is done
2010-11 is done
2011-12 is done
2012-13 is done
2013-14 is done
2014-15 is done
2015-16 is done
2016-17 is done
2017-18 is done
2018-19 is done
2019-20 is done
2020-21 is done
2021-22 is done

In [ ]:
df = pd.read_csv("TrainingData.csv")

In [9]:
df[df['TEAM_ABBREVIATION']=='MIA']

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,...,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK
23,21990,1610612748,MIA,Miami Heat,0029001096,1991-04-20,MIA @ NJN,L,240.0,36,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,21990,1610612748,MIA,Miami Heat,0029001084,1991-04-19,MIA vs. PHL,W,240.0,47,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69,21990,1610612748,MIA,Miami Heat,0029001072,1991-04-17,MIA vs. CHI,L,240.0,35,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,21990,1610612748,MIA,Miami Heat,0029001062,1991-04-16,MIA @ CHH,L,240.0,36,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,21990,1610612748,MIA,Miami Heat,0029001054,1991-04-14,MIA @ WAS,L,240.0,34,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49,NaN,1610612748,MIA,Miami Heat,0042100105,2022-04-26T00:00:00,MIA vs. ATL,W,48.0,37,...,104.0,90.0,55.0,4.0,92.0,12.0,84.0,52.0,97.0,48.0
61,NaN,1610612748,MIA,Miami Heat,0042100104,2022-04-24T00:00:00,MIA @ ATL,W,48.0,40,...,20.0,65.0,4.0,37.0,108.0,28.0,68.0,66.0,50.0,6.0
77,NaN,1610612748,MIA,Miami Heat,0042100103,2022-04-22T00:00:00,MIA @ ATL,L,48.0,41,...,38.0,10.0,65.0,65.0,72.0,28.0,68.0,79.0,50.0,60.0
90,NaN,1610612748,MIA,Miami Heat,0042100102,2022-04-19T00:00:00,MIA vs. ATL,W,48.0,38,...,98.0,74.0,65.0,26.0,21.0,12.0,76.0,18.0,28.0,26.0
104,NaN,1610612748,MIA,Miami Heat,0042100101,2022-04-17T00:00:00,MIA vs. ATL,W,48.0,43,...,60.0,1.0,65.0,4.0,72.0,12.0,54.0,90.0,28.0,6.0

In [531]:
# match games together

test_df = df.groupby("GAME_ID")

In [532]:
test_df = test_df.get_group('0022100012')

In [533]:
test_df

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE,SEASON_YEAR,BLKA,PFD,GP_RANK,W_RANK,L_RANK,W_PCT_RANK,MIN_RANK,FGM_RANK,FGA_RANK,FG_PCT_RANK,FG3M_RANK,FG3A_RANK,FG3_PCT_RANK,FTM_RANK,FTA_RANK,FT_PCT_RANK,OREB_RANK,DREB_RANK,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK
2452,NaN,1610612756,PHX,Phoenix Suns,0022100012,2021-10-20T00:00:00,PHX vs. DEN,L,48.0,36,87,0.414,14,37,0.378,12,17,0.706,11,34,45,23,9,3,18.0,18,98,-12.0,NaN,2021-22,1.0,20.0,1.0,1231.0,1231.0,1231.0,117.0,1902.0,1278.0,1968.0,686.0,872.0,889.0,1908.0,1782.0,1851.0,875.0,1133.0,1039.0,1407.0,2072.0,592.0,1631.0,37.0,724.0,994.0,2029.0,1912.0
2455,NaN,1610612743,DEN,Denver Nuggets,0022100012,2021-10-20T00:00:00,DEN @ PHX,W,48.0,44,83,0.530,17,39,0.436,5,9,0.556,6,40,46,25,9,1,19.0,20,110,12.0,NaN,2021-22,3.0,18.0,1.0,1.0,1.0,1.0,117.0,555.0,1815.0,273.0,223.0,628.0,385.0,2432.0,2391.0,2400.0,2077.0,305.0,925.0,1024.0,2204.0,592.0,2283.0,419.0,1233.0,1501.0,1226.0,491.0

In [534]:
row = pd.concat([test_df.iloc[0], test_df.iloc[1]], axis=0)

In [535]:
row

SEASON_ID                     NaN
TEAM_ID                1610612756
TEAM_ABBREVIATION             PHX
TEAM_NAME            Phoenix Suns
GAME_ID                0022100012
                         ...
BLKA_RANK                     419
PF_RANK                      1233
PFD_RANK                     1501
PTS_RANK                     1226
PLUS_MINUS_RANK               491
Length: 116, dtype: object

In [536]:
def groupGames(df):
    
    game_ids = df["GAME_ID"].unique()
    grouped_df = df.groupby("GAME_ID")

    row_1 = []
    row_2 = []
    for i in range(len(game_ids)):
        group = grouped_df.get_group(game_ids[i])
        row_1.append(group.iloc[0])
        row_2.append(group.iloc[1])
        
    row_1_df = pd.DataFrame(row_1)
    row_2_df = pd.DataFrame(row_2)
    
    row_2_df = row_2_df.add_prefix('OPP_')
    row_2_df = row_2_df.rename(columns={'OPP_GAME_ID': 'GAME_ID'})
    
    combined_df_1 = row_1_df.merge(row_2_df[['OPP_TEAM_NAME', 'GAME_ID','OPP_WL', 'OPP_MIN', 'OPP_FGM', 'OPP_FGA', 'OPP_FG_PCT', 'OPP_FG3M',
       'OPP_FG3A', 'OPP_FG3_PCT', 'OPP_FTM', 'OPP_FTA', 'OPP_FT_PCT', 'OPP_OREB', 'OPP_DREB', 'OPP_REB', 'OPP_AST',
       'OPP_STL', 'OPP_BLK', 'OPP_TOV', 'OPP_PF', 'OPP_PTS']], on="GAME_ID")
    
    row_1_df = pd.DataFrame(row_1)
    row_2_df = pd.DataFrame(row_2)
    
    row_1_df = row_1_df.add_prefix('OPP_')
    row_1_df = row_1_df.rename(columns={'OPP_GAME_ID': 'GAME_ID'})
    
    combined_df_2 = row_2_df.merge(row_1_df[['OPP_TEAM_NAME', 'GAME_ID','OPP_WL', 'OPP_MIN', 'OPP_FGM', 'OPP_FGA', 'OPP_FG_PCT', 'OPP_FG3M',
       'OPP_FG3A', 'OPP_FG3_PCT', 'OPP_FTM', 'OPP_FTA', 'OPP_FT_PCT', 'OPP_OREB', 'OPP_DREB', 'OPP_REB', 'OPP_AST',
       'OPP_STL', 'OPP_BLK', 'OPP_TOV', 'OPP_PF', 'OPP_PTS']], on="GAME_ID")
    
    combined_df = combined_df_1.append(combined_df_2)
    
    
    return combined_df

In [537]:
combined_df = groupGames(df)

In [538]:
combined_df.shape

(79588, 79)

In [539]:
df.shape

(79588, 58)

In [540]:
combined_df = combined_df.drop(['PLUS_MINUS','VIDEO_AVAILABLE','BLKA', 'PFD', 'GP_RANK', 'W_RANK', 'L_RANK',
       'W_PCT_RANK', 'MIN_RANK', 'FGM_RANK', 'FGA_RANK', 'FG_PCT_RANK',
       'FG3M_RANK', 'FG3A_RANK', 'FG3_PCT_RANK', 'FTM_RANK', 'FTA_RANK',
       'FT_PCT_RANK', 'OREB_RANK', 'DREB_RANK', 'REB_RANK', 'AST_RANK',
       'TOV_RANK', 'STL_RANK', 'BLK_RANK', 'BLKA_RANK', 'PF_RANK', 'PFD_RANK',
       'PTS_RANK', 'PLUS_MINUS_RANK'], 1)

In [541]:
combined_df.columns

Index(['SEASON_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME', 'GAME_ID',
       'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M',
       'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST',
       'STL', 'BLK', 'TOV', 'PF', 'PTS', 'SEASON_YEAR', 'OPP_TEAM_NAME',
       'OPP_WL', 'OPP_MIN', 'OPP_FGM', 'OPP_FGA', 'OPP_FG_PCT', 'OPP_FG3M',
       'OPP_FG3A', 'OPP_FG3_PCT', 'OPP_FTM', 'OPP_FTA', 'OPP_FT_PCT',
       'OPP_OREB', 'OPP_DREB', 'OPP_REB', 'OPP_AST', 'OPP_STL', 'OPP_BLK',
       'OPP_TOV', 'OPP_PF', 'OPP_PTS'],
      dtype='object')

In [542]:
def rolling_averages(group, cols, new_cols, amount):
    try:
        group = group.sort_values("GAME_DATE")
    except:
        pass
    rolling_stats = group[cols].shift(periods=1).rolling(amount).mean() # the 3 before
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    
    return group

In [543]:
cols = ['FGM', 'FGA', 'FG_PCT', 'FG3M',
       'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST',
       'STL', 'BLK', 'TOV', 'PF', 'PTS']
new_cols = [f"{c}_rolling_3" for c in cols]

rolling_df = combined_df.groupby("TEAM_ID").apply(lambda x: rolling_averages(x, cols, new_cols, 3))
rolling_df = rolling_df.droplevel('TEAM_ID').reset_index().drop('index', axis=1)

In [544]:
cols = ['OPP_FGM', 'OPP_FGA',
       'OPP_FG_PCT', 'OPP_FG3M', 'OPP_FG3A', 'OPP_FG3_PCT',
       'OPP_FTM', 'OPP_FTA', 'OPP_FT_PCT', 'OPP_OREB',
       'OPP_DREB', 'OPP_REB', 'OPP_AST', 'OPP_STL',
       'OPP_BLK', 'OPP_TOV', 'OPP_PF', 'OPP_PTS']
new_cols = [f"{c}_rolling_3" for c in cols]

rolling_df = rolling_df.groupby("TEAM_ID").apply(lambda x: rolling_averages(x, cols, new_cols, 3))
rolling_df = rolling_df.droplevel('TEAM_ID').reset_index().drop('index', axis=1)

In [545]:
cols = ['FGM', 'FGA', 'FG_PCT', 'FG3M',
       'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST',
       'STL', 'BLK', 'TOV', 'PF', 'PTS']
new_cols = [f"{c}_rolling_15" for c in cols]

rolling_df = rolling_df.groupby("TEAM_ID").apply(lambda x: rolling_averages(x, cols, new_cols, 15))
rolling_df = rolling_df.droplevel('TEAM_ID').reset_index().drop('index', axis=1)

In [546]:
cols = ['OPP_FGM', 'OPP_FGA',
       'OPP_FG_PCT', 'OPP_FG3M', 'OPP_FG3A', 'OPP_FG3_PCT',
       'OPP_FTM', 'OPP_FTA', 'OPP_FT_PCT', 'OPP_OREB',
       'OPP_DREB', 'OPP_REB', 'OPP_AST', 'OPP_STL',
       'OPP_BLK', 'OPP_TOV', 'OPP_PF', 'OPP_PTS']
new_cols = [f"{c}_rolling_15" for c in cols]

rolling_df = rolling_df.groupby("TEAM_ID").apply(lambda x: rolling_averages(x, cols, new_cols, 15))
rolling_df = rolling_df.droplevel('TEAM_ID').reset_index().drop('index', axis=1)

# The model, win classifier

In [547]:
rolling_df["target"] = (rolling_df["WL"] == "W").astype("int") # count draw and loss as not a win

In [548]:
rolling_df["is_home"] = (rolling_df["MATCHUP"].str.contains("vs.")).astype("int")

In [549]:
print(rolling_df.columns.tolist())

['SEASON_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME', 'GAME_ID', 'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'SEASON_YEAR', 'OPP_TEAM_NAME', 'OPP_WL', 'OPP_MIN', 'OPP_FGM', 'OPP_FGA', 'OPP_FG_PCT', 'OPP_FG3M', 'OPP_FG3A', 'OPP_FG3_PCT', 'OPP_FTM', 'OPP_FTA', 'OPP_FT_PCT', 'OPP_OREB', 'OPP_DREB', 'OPP_REB', 'OPP_AST', 'OPP_STL', 'OPP_BLK', 'OPP_TOV', 'OPP_PF', 'OPP_PTS', 'FGM_rolling_3', 'FGA_rolling_3', 'FG_PCT_rolling_3', 'FG3M_rolling_3', 'FG3A_rolling_3', 'FG3_PCT_rolling_3', 'FTM_rolling_3', 'FTA_rolling_3', 'FT_PCT_rolling_3', 'OREB_rolling_3', 'DREB_rolling_3', 'REB_rolling_3', 'AST_rolling_3', 'STL_rolling_3', 'BLK_rolling_3', 'TOV_rolling_3', 'PF_rolling_3', 'PTS_rolling_3', 'OPP_FGM_rolling_3', 'OPP_FGA_rolling_3', 'OPP_FG_PCT_rolling_3', 'OPP_FG3M_rolling_3', 'OPP_FG3A_rolling_3', 'OPP_FG3_PCT_rolling_3', 'OPP_FTM_rolling_3', 'OPP_FTA_rolling_3', 'OPP_FT_PCT_rolling_3', 'OPP_OREB_rolling_3', 'OPP_DREB_rolling_3', 'OPP_REB_rolling_3', 'OPP_AST_rolling_3', 'OPP_STL_rolling_3', 'OPP_BLK_rolling_3', 'OPP_TOV_rolling_3', 'OPP_PF_rolling_3', 'OPP_PTS_rolling_3', 'FGM_rolling_15', 'FGA_rolling_15', 'FG_PCT_rolling_15', 'FG3M_rolling_15', 'FG3A_rolling_15', 'FG3_PCT_rolling_15', 'FTM_rolling_15', 'FTA_rolling_15', 'FT_PCT_rolling_15', 'OREB_rolling_15', 'DREB_rolling_15', 'REB_rolling_15', 'AST_rolling_15', 'STL_rolling_15', 'BLK_rolling_15', 'TOV_rolling_15', 'PF_rolling_15', 'PTS_rolling_15', 'OPP_FGM_rolling_15', 'OPP_FGA_rolling_15', 'OPP_FG_PCT_rolling_15', 'OPP_FG3M_rolling_15', 'OPP_FG3A_rolling_15', 'OPP_FG3_PCT_rolling_15', 'OPP_FTM_rolling_15', 'OPP_FTA_rolling_15', 'OPP_FT_PCT_rolling_15', 'OPP_OREB_rolling_15', 'OPP_DREB_rolling_15', 'OPP_REB_rolling_15', 'OPP_AST_rolling_15', 'OPP_STL_rolling_15', 'OPP_BLK_rolling_15', 'OPP_TOV_rolling_15', 'OPP_PF_rolling_15', 'OPP_PTS_rolling_15', 'target', 'is_home']

In [600]:
predictors = predictors =[
     'FGM_rolling_3', 'FGA_rolling_3', 'FG_PCT_rolling_3', 'FG3M_rolling_3', 'FG3A_rolling_3', 'FG3_PCT_rolling_3', 'FTM_rolling_3', 'FTA_rolling_3', 'FT_PCT_rolling_3', 'OREB_rolling_3', 'DREB_rolling_3', 'REB_rolling_3', 'AST_rolling_3', 'STL_rolling_3', 'BLK_rolling_3', 'TOV_rolling_3', 'PF_rolling_3', 'PTS_rolling_3', 'OPP_FGM_rolling_3', 'OPP_FGA_rolling_3', 'OPP_FG_PCT_rolling_3', 'OPP_FG3M_rolling_3', 'OPP_FG3A_rolling_3', 'OPP_FG3_PCT_rolling_3', 'OPP_FTM_rolling_3', 'OPP_FTA_rolling_3', 'OPP_FT_PCT_rolling_3', 'OPP_OREB_rolling_3', 'OPP_DREB_rolling_3', 'OPP_REB_rolling_3', 'OPP_AST_rolling_3', 'OPP_STL_rolling_3', 'OPP_BLK_rolling_3', 'OPP_TOV_rolling_3', 'OPP_PF_rolling_3', 'OPP_PTS_rolling_3', 'FGM_rolling_15', 'FGA_rolling_15', 'FG_PCT_rolling_15', 'FG3M_rolling_15', 'FG3A_rolling_15', 'FG3_PCT_rolling_15', 'FTM_rolling_15', 'FTA_rolling_15', 'FT_PCT_rolling_15', 'OREB_rolling_15', 'DREB_rolling_15', 'REB_rolling_15', 'AST_rolling_15', 'STL_rolling_15', 'BLK_rolling_15', 'TOV_rolling_15', 'PF_rolling_15', 'PTS_rolling_15', 'OPP_FGM_rolling_15', 'OPP_FGA_rolling_15', 'OPP_FG_PCT_rolling_15', 'OPP_FG3M_rolling_15', 'OPP_FG3A_rolling_15', 'OPP_FG3_PCT_rolling_15', 'OPP_FTM_rolling_15', 'OPP_FTA_rolling_15', 'OPP_FT_PCT_rolling_15', 'OPP_OREB_rolling_15', 'OPP_DREB_rolling_15', 'OPP_REB_rolling_15', 'OPP_AST_rolling_15', 'OPP_STL_rolling_15', 'OPP_BLK_rolling_15', 'OPP_TOV_rolling_15', 'OPP_PF_rolling_15', 'OPP_PTS_rolling_15', 'is_home'
]

In [601]:
'''
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

rolling_df[predictors] = scaler.fit_transform(rolling_df[predictors])
'''

'\nfrom sklearn.preprocessing import MinMaxScaler\nscaler = MinMaxScaler()\n\nrolling_df[predictors] = scaler.fit_transform(rolling_df[predictors])\n'

In [602]:
from sklearn.metrics import precision_score

def train_test_model(data, predictors, model):
    train = data[data["SEASON_YEAR"] < '2021-22']
    test = data[data["SEASON_YEAR"] > '2020-21']
    
    model.fit(train[predictors], train["target"])
    
    predictions = model.predict(test[predictors])
    
    combined = pd.DataFrame(dict(actual=test["target"], prediction=predictions))
    results = pd.crosstab(index=combined["actual"],columns=combined["prediction"])
    
    precision = precision_score(test["target"], predictions)
    
    combined = combined.merge(data[["GAME_DATE","TEAM_NAME","OPP_TEAM_NAME","WL"]], left_index=True, right_index=True)
    
    return combined, precision, results, model

def make_predictions(data, predictors, model):
    values = [data[predictors].values]
    
    prediction = model.predict(values)[0]
    
    prediction_df = data[["TEAM_NAME","MATCHUP"]] 
    if prediction == 0:
        prediction_df["Prediction"] = "L"
    else:
        prediction_df["Prediction"] = "W"
    
    
    return prediction_df

In [603]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

combined, precision, results, rf = train_test_model(rolling_df, predictors, rf)

In [604]:
combined

,actual,prediction,GAME_DATE,TEAM_NAME,OPP_TEAM_NAME,WL
2593,1,0,2021-10-21T00:00:00,Atlanta Hawks,Dallas Mavericks,W
2594,0,0,2021-10-23T00:00:00,Atlanta Hawks,Cleveland Cavaliers,L
2595,1,0,2021-10-25T00:00:00,Atlanta Hawks,Detroit Pistons,W
2596,1,0,2021-10-27T00:00:00,Atlanta Hawks,New Orleans Pelicans,W
2597,0,0,2021-10-28T00:00:00,Atlanta Hawks,Washington Wizards,L
...,...,...,...,...,...,...
77391,0,0,2022-04-02T00:00:00,Charlotte Hornets,Philadelphia 76ers,L
77392,0,0,2022-04-05T00:00:00,Charlotte Hornets,Miami Heat,L
77393,1,1,2022-04-07T00:00:00,Charlotte Hornets,Orlando Magic,W
77394,1,1,2022-04-08T00:00:00,Charlotte Hornets,Chicago Bulls,W
77395,1,1,2022-04-10T00:00:00,Charlotte Hornets,Washington Wizards,W

In [605]:
precision

0.5732383214568487

In [606]:
results

prediction    0    1
actual
0           750  539
1           565  724

# WOW

In [607]:
pd.set_option('display.max_rows', 10)

In [608]:
from nba_api.stats.endpoints import leaguedashteamstats

In [609]:
sixers = leaguedashteamstats.LeagueDashTeamStats(team_id_nullable=1610612755, per_mode_detailed="PerGame").get_data_frames()[0] # sixers

In [610]:
sixers.columns

Index(['TEAM_ID', 'TEAM_NAME', 'GP', 'W', 'L', 'W_PCT', 'MIN', 'FGM', 'FGA',
       'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB',
       'DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', 'PTS',
       'PLUS_MINUS', 'GP_RANK', 'W_RANK', 'L_RANK', 'W_PCT_RANK', 'MIN_RANK',
       'FGM_RANK', 'FGA_RANK', 'FG_PCT_RANK', 'FG3M_RANK', 'FG3A_RANK',
       'FG3_PCT_RANK', 'FTM_RANK', 'FTA_RANK', 'FT_PCT_RANK', 'OREB_RANK',
       'DREB_RANK', 'REB_RANK', 'AST_RANK', 'TOV_RANK', 'STL_RANK', 'BLK_RANK',
       'BLKA_RANK', 'PF_RANK', 'PFD_RANK', 'PTS_RANK', 'PLUS_MINUS_RANK',
       'CFID', 'CFPARAMS'],
      dtype='object')

In [611]:
rolling_df.columns

Index(['SEASON_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME', 'GAME_ID',
       'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'FGM',
       ...
       'OPP_DREB_rolling_15', 'OPP_REB_rolling_15', 'OPP_AST_rolling_15',
       'OPP_STL_rolling_15', 'OPP_BLK_rolling_15', 'OPP_TOV_rolling_15',
       'OPP_PF_rolling_15', 'OPP_PTS_rolling_15', 'target', 'is_home'],
      dtype='object', length=123)

In [612]:
sixers = sixers[['TEAM_ID', 'TEAM_NAME', 'GP', 'W', 'L', 'W_PCT', 'MIN', 'FGM', 'FGA',
       'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB',
       'DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK', 'PF', 'PFD', 'PTS']]

In [613]:
sixers.columns

Index(['TEAM_ID', 'TEAM_NAME', 'GP', 'W', 'L', 'W_PCT', 'MIN', 'FGM', 'FGA',
       'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB',
       'DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK', 'PF', 'PFD', 'PTS'],
      dtype='object')

In [614]:
sixers_opp = leaguedashteamstats.LeagueDashTeamStats(team_id_nullable=1610612748,   per_mode_detailed="PerGame").get_data_frames()[0] # sixers

In [615]:
sixers_opp.columns

Index(['TEAM_ID', 'TEAM_NAME', 'GP', 'W', 'L', 'W_PCT', 'MIN', 'FGM', 'FGA',
       'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB',
       'DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', 'PTS',
       'PLUS_MINUS', 'GP_RANK', 'W_RANK', 'L_RANK', 'W_PCT_RANK', 'MIN_RANK',
       'FGM_RANK', 'FGA_RANK', 'FG_PCT_RANK', 'FG3M_RANK', 'FG3A_RANK',
       'FG3_PCT_RANK', 'FTM_RANK', 'FTA_RANK', 'FT_PCT_RANK', 'OREB_RANK',
       'DREB_RANK', 'REB_RANK', 'AST_RANK', 'TOV_RANK', 'STL_RANK', 'BLK_RANK',
       'BLKA_RANK', 'PF_RANK', 'PFD_RANK', 'PTS_RANK', 'PLUS_MINUS_RANK',
       'CFID', 'CFPARAMS'],
      dtype='object')

In [616]:
sixers_opp = sixers_opp.add_prefix('OPP_')

sixers_opp = sixers_opp[['OPP_FGM', 'OPP_FGA',
       'OPP_FG_PCT', 'OPP_FG3M', 'OPP_FG3A', 'OPP_FG3_PCT', 'OPP_FTM', 'OPP_FTA', 'OPP_FT_PCT', 'OPP_OREB',
       'OPP_DREB', 'OPP_REB', 'OPP_AST', 'OPP_TOV', 'OPP_STL', 'OPP_BLK', 'OPP_PF', 'OPP_PFD', 'OPP_PTS']]

In [617]:
sixers = sixers.join(sixers_opp)

In [618]:
sixers

,TEAM_ID,TEAM_NAME,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,PF,PFD,PTS,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_FG3M,OPP_FG3A,OPP_FG3_PCT,OPP_FTM,OPP_FTA,OPP_FT_PCT,OPP_OREB,OPP_DREB,OPP_REB,OPP_AST,OPP_TOV,OPP_STL,OPP_BLK,OPP_PF,OPP_PFD,OPP_PTS
0,1610612755,Philadelphia 76ers,82,51,31,0.622,48.3,39.4,84.5,0.466,11.6,31.8,0.364,19.6,23.8,0.821,8.5,33.8,42.3,23.7,12.5,7.7,5.3,19.4,19.4,109.9,39.6,84.8,0.467,13.6,35.8,0.379,17.3,21.4,0.808,9.8,33.9,43.7,25.5,14.6,7.4,3.2,20.5,20.6,110.0

In [619]:
sixers_stats = combined_df[combined_df['TEAM_ID'] == 1610612755]
sixers_stats["is_home"] = (sixers_stats["MATCHUP"].str.contains("vs.")).astype("int")

<ipython-input-619-4e2ea855ceb9>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sixers_stats["is_home"] = (sixers_stats["MATCHUP"].str.contains("vs.")).astype("int")

In [620]:
sixers_stats

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,SEASON_YEAR,OPP_TEAM_NAME,OPP_WL,OPP_MIN,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_FG3M,OPP_FG3A,OPP_FG3_PCT,OPP_FTM,OPP_FTA,OPP_FT_PCT,OPP_OREB,OPP_DREB,OPP_REB,OPP_AST,OPP_STL,OPP_BLK,OPP_TOV,OPP_PF,OPP_PTS,is_home
2,21990,1610612755,PHL,Philadelphia 76ers,0029001097,1991-04-21,PHL @ CLE,L,240.0,46,103,0.447,2,5,0.400,16,22,0.727,15,32,47,29,9,5,13.0,27,110,NaN,Cleveland Cavaliers,W,240.0,47,89,0.528,3,11,0.273,26,34,0.765,9,39,48,36,9,7,13.0,20,123,0
22,21990,1610612755,PHL,Philadelphia 76ers,0029001084,1991-04-19,PHL @ MIA,L,240.0,40,79,0.506,1,4,0.250,19,24,0.792,6,29,35,18,11,10,20.0,19,100,NaN,Miami Heat,W,240.0,47,105,0.448,0,2,0.000,20,26,0.769,24,29,53,24,12,6,14.0,18,114,0
55,21990,1610612755,PHL,Philadelphia 76ers,0029001050,1991-04-14,PHL vs. MIN,L,240.0,33,77,0.429,0,7,0.000,22,26,0.846,13,31,44,21,6,5,17.0,21,88,NaN,Minnesota Timberwolves,W,240.0,35,84,0.417,1,5,0.200,25,29,0.862,16,29,45,21,9,2,13.0,25,96,1
73,21990,1610612755,PHL,Philadelphia 76ers,0029001041,1991-04-12,PHL vs. WAS,L,240.0,30,81,0.370,0,4,0.000,25,30,0.833,13,28,41,19,8,4,12.0,12,85,NaN,Washington Bullets,W,240.0,43,91,0.473,0,6,0.000,9,13,0.692,13,32,45,35,8,9,10.0,20,95,1
84,21990,1610612755,PHL,Philadelphia 76ers,0029001024,1991-04-10,PHL vs. NYK,W,240.0,38,79,0.481,4,8,0.500,20,24,0.833,12,37,49,28,7,5,17.0,20,100,NaN,New York Knicks,L,240.0,35,82,0.427,2,4,0.500,12,18,0.667,9,22,31,26,11,6,13.0,21,84,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39747,NaN,1610612755,PHI,Philadelphia 76ers,0042100201,2022-05-02T00:00:00,PHI @ MIA,L,48.0,34,79,0.430,6,34,0.176,18,20,0.900,9,28,37,18,4,6,15.0,17,92,2021-22,Miami Heat,W,48.0,40,92,0.435,9,36,0.250,17,18,0.944,15,32,47,21,5,2,13.0,18,106,0
39754,NaN,1610612755,PHI,Philadelphia 76ers,0042100136,2022-04-28T00:00:00,PHI @ TOR,W,48.0,47,81,0.580,16,40,0.400,22,23,0.957,10,37,47,32,4,4,11.0,22,132,2021-22,Toronto Raptors,L,48.0,35,89,0.393,7,35,0.200,20,25,0.800,15,22,37,15,6,1,10.0,22,97,0
39779,NaN,1610612755,PHI,Philadelphia 76ers,0042100133,2022-04-20T00:00:00,PHI @ TOR,W,53.0,38,74,0.514,13,31,0.419,15,20,0.750,9,37,46,18,5,3,24.0,21,104,2021-22,Toronto Raptors,L,53.0,38,86,0.442,13,35,0.371,12,18,0.667,9,23,32,23,9,4,11.0,21,101,0
39784,NaN,1610612755,PHI,Philadelphia 76ers,0042100132,2022-04-18T00:00:00,PHI vs. TOR,W,48.0,36,69,0.522,14,30,0.467,26,30,0.867,7,34,41,20,5,12,16.0,18,112,2021-22,Toronto Raptors,L,48.0,38,89,0.427,11,32,0.344,10,12,0.833,13,22,35,16,7,4,11.0,24,97,1
39792,NaN,1610612755,PHI,Philadelphia 76ers,0042100131,2022-04-16T00:00:00,PHI vs. TOR,W,48.0,43,84,0.512,16,32,0.500,29,34,0.853,10,29,39,29,6,4,4.0,18,131,2021-22,Toronto Raptors,L,48.0,40,82,0.488,12,30,0.400,19,23,0.826,7,29,36,27,1,8,8.0,26,111,1

In [621]:
combined_df.columns

Index(['SEASON_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME', 'GAME_ID',
       'GAME_DATE', 'MATCHUP', 'WL', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M',
       'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST',
       'STL', 'BLK', 'TOV', 'PF', 'PTS', 'SEASON_YEAR', 'OPP_TEAM_NAME',
       'OPP_WL', 'OPP_MIN', 'OPP_FGM', 'OPP_FGA', 'OPP_FG_PCT', 'OPP_FG3M',
       'OPP_FG3A', 'OPP_FG3_PCT', 'OPP_FTM', 'OPP_FTA', 'OPP_FT_PCT',
       'OPP_OREB', 'OPP_DREB', 'OPP_REB', 'OPP_AST', 'OPP_STL', 'OPP_BLK',
       'OPP_TOV', 'OPP_PF', 'OPP_PTS'],
      dtype='object')

In [622]:
sixers_stats = sixers_stats[['TEAM_ID','TEAM_NAME','MATCHUP','FGM', 'FGA', 'FG_PCT', 'FG3M',
       'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST',
       'STL', 'BLK', 'TOV', 'PF', 'PTS','OPP_FGM', 'OPP_FGA', 'OPP_FG_PCT', 'OPP_FG3M',
       'OPP_FG3A', 'OPP_FG3_PCT', 'OPP_FTM', 'OPP_FTA', 'OPP_FT_PCT',
       'OPP_OREB', 'OPP_DREB', 'OPP_REB', 'OPP_AST', 'OPP_STL', 'OPP_BLK',
       'OPP_TOV', 'OPP_PF', 'OPP_PTS','WL','is_home']]

In [623]:
sixers_stats["target"] = (sixers_stats["WL"] == "W").astype("int") # count draw and loss as not a win

<ipython-input-623-84071f0af730>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sixers_stats["target"] = (sixers_stats["WL"] == "W").astype("int") # count draw and loss as not a win

In [624]:
sixers_stats = sixers_stats[['TEAM_ID','TEAM_NAME','MATCHUP','FGM', 'FGA', 'FG_PCT', 'FG3M',
       'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST',
       'STL', 'BLK', 'TOV', 'PF', 'PTS','OPP_FGM', 'OPP_FGA', 'OPP_FG_PCT', 'OPP_FG3M',
       'OPP_FG3A', 'OPP_FG3_PCT', 'OPP_FTM', 'OPP_FTA', 'OPP_FT_PCT',
       'OPP_OREB', 'OPP_DREB', 'OPP_REB', 'OPP_AST', 'OPP_STL', 'OPP_BLK',
       'OPP_TOV', 'OPP_PF', 'OPP_PTS','target','is_home']]

In [625]:
sixers_stats

,TEAM_ID,TEAM_NAME,MATCHUP,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_FG3M,OPP_FG3A,OPP_FG3_PCT,OPP_FTM,OPP_FTA,OPP_FT_PCT,OPP_OREB,OPP_DREB,OPP_REB,OPP_AST,OPP_STL,OPP_BLK,OPP_TOV,OPP_PF,OPP_PTS,target,is_home
2,1610612755,Philadelphia 76ers,PHL @ CLE,46,103,0.447,2,5,0.400,16,22,0.727,15,32,47,29,9,5,13.0,27,110,47,89,0.528,3,11,0.273,26,34,0.765,9,39,48,36,9,7,13.0,20,123,0,0
22,1610612755,Philadelphia 76ers,PHL @ MIA,40,79,0.506,1,4,0.250,19,24,0.792,6,29,35,18,11,10,20.0,19,100,47,105,0.448,0,2,0.000,20,26,0.769,24,29,53,24,12,6,14.0,18,114,0,0
55,1610612755,Philadelphia 76ers,PHL vs. MIN,33,77,0.429,0,7,0.000,22,26,0.846,13,31,44,21,6,5,17.0,21,88,35,84,0.417,1,5,0.200,25,29,0.862,16,29,45,21,9,2,13.0,25,96,0,1
73,1610612755,Philadelphia 76ers,PHL vs. WAS,30,81,0.370,0,4,0.000,25,30,0.833,13,28,41,19,8,4,12.0,12,85,43,91,0.473,0,6,0.000,9,13,0.692,13,32,45,35,8,9,10.0,20,95,0,1
84,1610612755,Philadelphia 76ers,PHL vs. NYK,38,79,0.481,4,8,0.500,20,24,0.833,12,37,49,28,7,5,17.0,20,100,35,82,0.427,2,4,0.500,12,18,0.667,9,22,31,26,11,6,13.0,21,84,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39747,1610612755,Philadelphia 76ers,PHI @ MIA,34,79,0.430,6,34,0.176,18,20,0.900,9,28,37,18,4,6,15.0,17,92,40,92,0.435,9,36,0.250,17,18,0.944,15,32,47,21,5,2,13.0,18,106,0,0
39754,1610612755,Philadelphia 76ers,PHI @ TOR,47,81,0.580,16,40,0.400,22,23,0.957,10,37,47,32,4,4,11.0,22,132,35,89,0.393,7,35,0.200,20,25,0.800,15,22,37,15,6,1,10.0,22,97,1,0
39779,1610612755,Philadelphia 76ers,PHI @ TOR,38,74,0.514,13,31,0.419,15,20,0.750,9,37,46,18,5,3,24.0,21,104,38,86,0.442,13,35,0.371,12,18,0.667,9,23,32,23,9,4,11.0,21,101,1,0
39784,1610612755,Philadelphia 76ers,PHI vs. TOR,36,69,0.522,14,30,0.467,26,30,0.867,7,34,41,20,5,12,16.0,18,112,38,89,0.427,11,32,0.344,10,12,0.833,13,22,35,16,7,4,11.0,24,97,1,1
39792,1610612755,Philadelphia 76ers,PHI vs. TOR,43,84,0.512,16,32,0.500,29,34,0.853,10,29,39,29,6,4,4.0,18,131,40,82,0.488,12,30,0.400,19,23,0.826,7,29,36,27,1,8,8.0,26,111,1,1

In [626]:
sixers.columns

Index(['TEAM_ID', 'TEAM_NAME', 'GP', 'W', 'L', 'W_PCT', 'MIN', 'FGM', 'FGA',
       'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB',
       'DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK', 'PF', 'PFD', 'PTS',
       'OPP_FGM', 'OPP_FGA', 'OPP_FG_PCT', 'OPP_FG3M', 'OPP_FG3A',
       'OPP_FG3_PCT', 'OPP_FTM', 'OPP_FTA', 'OPP_FT_PCT', 'OPP_OREB',
       'OPP_DREB', 'OPP_REB', 'OPP_AST', 'OPP_TOV', 'OPP_STL', 'OPP_BLK',
       'OPP_PF', 'OPP_PFD', 'OPP_PTS'],
      dtype='object')

In [627]:
sixers_stats.columns

Index(['TEAM_ID', 'TEAM_NAME', 'MATCHUP', 'FGM', 'FGA', 'FG_PCT', 'FG3M',
       'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST',
       'STL', 'BLK', 'TOV', 'PF', 'PTS', 'OPP_FGM', 'OPP_FGA', 'OPP_FG_PCT',
       'OPP_FG3M', 'OPP_FG3A', 'OPP_FG3_PCT', 'OPP_FTM', 'OPP_FTA',
       'OPP_FT_PCT', 'OPP_OREB', 'OPP_DREB', 'OPP_REB', 'OPP_AST', 'OPP_STL',
       'OPP_BLK', 'OPP_TOV', 'OPP_PF', 'OPP_PTS', 'target', 'is_home'],
      dtype='object')

In [628]:
sixers["is_home"] = 1
sixers = sixers[['TEAM_ID','FGM', 'FGA',
       'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB',
       'DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK', 'PF', 'PTS',
       'OPP_FGM', 'OPP_FGA', 'OPP_FG_PCT', 'OPP_FG3M', 'OPP_FG3A',
       'OPP_FG3_PCT', 'OPP_FTM', 'OPP_FTA', 'OPP_FT_PCT', 'OPP_OREB',
       'OPP_DREB', 'OPP_REB', 'OPP_AST', 'OPP_TOV', 'OPP_STL', 'OPP_BLK',
       'OPP_PF', 'OPP_PTS','is_home']]

In [629]:
sixers.columns

Index(['TEAM_ID', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM',
       'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK',
       'PF', 'PTS', 'OPP_FGM', 'OPP_FGA', 'OPP_FG_PCT', 'OPP_FG3M', 'OPP_FG3A',
       'OPP_FG3_PCT', 'OPP_FTM', 'OPP_FTA', 'OPP_FT_PCT', 'OPP_OREB',
       'OPP_DREB', 'OPP_REB', 'OPP_AST', 'OPP_TOV', 'OPP_STL', 'OPP_BLK',
       'OPP_PF', 'OPP_PTS', 'is_home'],
      dtype='object')

In [630]:
sixers["target"] = 0
sixers["TEAM_NAME"] = "Philadelphia 76ers"
sixers["MATCHUP"] = "Philadelphia 76ers @ Miami Heat"

<ipython-input-630-3806801c9a1c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sixers["target"] = 0
<ipython-input-630-3806801c9a1c>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sixers["TEAM_NAME"] = "Philadelphia 76ers"
<ipython-input-630-3806801c9a1c>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sixers["MATCHUP"] = "Philadelphia 76ers @ Miami Heat"

In [631]:
input_data = sixers_stats.append(sixers)

In [632]:
input_data # last row can now be input data

,TEAM_ID,TEAM_NAME,MATCHUP,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_FG3M,OPP_FG3A,OPP_FG3_PCT,OPP_FTM,OPP_FTA,OPP_FT_PCT,OPP_OREB,OPP_DREB,OPP_REB,OPP_AST,OPP_STL,OPP_BLK,OPP_TOV,OPP_PF,OPP_PTS,target,is_home
2,1610612755,Philadelphia 76ers,PHL @ CLE,46.0,103.0,0.447,2.0,5.0,0.400,16.0,22.0,0.727,15.0,32.0,47.0,29.0,9.0,5.0,13.0,27.0,110.0,47.0,89.0,0.528,3.0,11.0,0.273,26.0,34.0,0.765,9.0,39.0,48.0,36.0,9.0,7.0,13.0,20.0,123.0,0,0
22,1610612755,Philadelphia 76ers,PHL @ MIA,40.0,79.0,0.506,1.0,4.0,0.250,19.0,24.0,0.792,6.0,29.0,35.0,18.0,11.0,10.0,20.0,19.0,100.0,47.0,105.0,0.448,0.0,2.0,0.000,20.0,26.0,0.769,24.0,29.0,53.0,24.0,12.0,6.0,14.0,18.0,114.0,0,0
55,1610612755,Philadelphia 76ers,PHL vs. MIN,33.0,77.0,0.429,0.0,7.0,0.000,22.0,26.0,0.846,13.0,31.0,44.0,21.0,6.0,5.0,17.0,21.0,88.0,35.0,84.0,0.417,1.0,5.0,0.200,25.0,29.0,0.862,16.0,29.0,45.0,21.0,9.0,2.0,13.0,25.0,96.0,0,1
73,1610612755,Philadelphia 76ers,PHL vs. WAS,30.0,81.0,0.370,0.0,4.0,0.000,25.0,30.0,0.833,13.0,28.0,41.0,19.0,8.0,4.0,12.0,12.0,85.0,43.0,91.0,0.473,0.0,6.0,0.000,9.0,13.0,0.692,13.0,32.0,45.0,35.0,8.0,9.0,10.0,20.0,95.0,0,1
84,1610612755,Philadelphia 76ers,PHL vs. NYK,38.0,79.0,0.481,4.0,8.0,0.500,20.0,24.0,0.833,12.0,37.0,49.0,28.0,7.0,5.0,17.0,20.0,100.0,35.0,82.0,0.427,2.0,4.0,0.500,12.0,18.0,0.667,9.0,22.0,31.0,26.0,11.0,6.0,13.0,21.0,84.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39754,1610612755,Philadelphia 76ers,PHI @ TOR,47.0,81.0,0.580,16.0,40.0,0.400,22.0,23.0,0.957,10.0,37.0,47.0,32.0,4.0,4.0,11.0,22.0,132.0,35.0,89.0,0.393,7.0,35.0,0.200,20.0,25.0,0.800,15.0,22.0,37.0,15.0,6.0,1.0,10.0,22.0,97.0,1,0
39779,1610612755,Philadelphia 76ers,PHI @ TOR,38.0,74.0,0.514,13.0,31.0,0.419,15.0,20.0,0.750,9.0,37.0,46.0,18.0,5.0,3.0,24.0,21.0,104.0,38.0,86.0,0.442,13.0,35.0,0.371,12.0,18.0,0.667,9.0,23.0,32.0,23.0,9.0,4.0,11.0,21.0,101.0,1,0
39784,1610612755,Philadelphia 76ers,PHI vs. TOR,36.0,69.0,0.522,14.0,30.0,0.467,26.0,30.0,0.867,7.0,34.0,41.0,20.0,5.0,12.0,16.0,18.0,112.0,38.0,89.0,0.427,11.0,32.0,0.344,10.0,12.0,0.833,13.0,22.0,35.0,16.0,7.0,4.0,11.0,24.0,97.0,1,1
39792,1610612755,Philadelphia 76ers,PHI vs. TOR,43.0,84.0,0.512,16.0,32.0,0.500,29.0,34.0,0.853,10.0,29.0,39.0,29.0,6.0,4.0,4.0,18.0,131.0,40.0,82.0,0.488,12.0,30.0,0.400,19.0,23.0,0.826,7.0,29.0,36.0,27.0,1.0,8.0,8.0,26.0,111.0,1,1
0,1610612755,Philadelphia 76ers,Philadelphia 76ers @ Miami Heat,39.4,84.5,0.466,11.6,31.8,0.364,19.6,23.8,0.821,8.5,33.8,42.3,23.7,7.7,5.3,12.5,19.4,109.9,39.6,84.8,0.467,13.6,35.8,0.379,17.3,21.4,0.808,9.8,33.9,43.7,25.5,7.4,3.2,14.6,20.5,110.0,0,1

In [633]:
input_data.columns

Index(['TEAM_ID', 'TEAM_NAME', 'MATCHUP', 'FGM', 'FGA', 'FG_PCT', 'FG3M',
       'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST',
       'STL', 'BLK', 'TOV', 'PF', 'PTS', 'OPP_FGM', 'OPP_FGA', 'OPP_FG_PCT',
       'OPP_FG3M', 'OPP_FG3A', 'OPP_FG3_PCT', 'OPP_FTM', 'OPP_FTA',
       'OPP_FT_PCT', 'OPP_OREB', 'OPP_DREB', 'OPP_REB', 'OPP_AST', 'OPP_STL',
       'OPP_BLK', 'OPP_TOV', 'OPP_PF', 'OPP_PTS', 'target', 'is_home'],
      dtype='object')

In [634]:
cols = ['FGM', 'FGA', 'FG_PCT', 'FG3M',
       'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST',
       'STL', 'BLK', 'TOV', 'PF', 'PTS']
new_cols = [f"{c}_rolling_3" for c in cols]

input_data_rolling = input_data.groupby("TEAM_ID").apply(lambda x: rolling_averages(x, cols, new_cols, 3))
input_data_rolling= input_data_rolling.droplevel('TEAM_ID').reset_index().drop('index', axis=1)

In [635]:
cols = ['OPP_FGM', 'OPP_FGA',
       'OPP_FG_PCT', 'OPP_FG3M', 'OPP_FG3A', 'OPP_FG3_PCT',
       'OPP_FTM', 'OPP_FTA', 'OPP_FT_PCT', 'OPP_OREB',
       'OPP_DREB', 'OPP_REB', 'OPP_AST', 'OPP_STL',
       'OPP_BLK', 'OPP_TOV', 'OPP_PF', 'OPP_PTS']
new_cols = [f"{c}_rolling_3" for c in cols]

input_data_rolling = input_data_rolling.groupby("TEAM_ID").apply(lambda x: rolling_averages(x, cols, new_cols, 3))
input_data_rolling = input_data_rolling.droplevel('TEAM_ID').reset_index().drop('index', axis=1)

In [636]:
cols = ['FGM', 'FGA', 'FG_PCT', 'FG3M',
       'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST',
       'STL', 'BLK', 'TOV', 'PF', 'PTS']
new_cols = [f"{c}_rolling_15" for c in cols]

input_data_rolling = input_data_rolling.groupby("TEAM_ID").apply(lambda x: rolling_averages(x, cols, new_cols, 15))
input_data_rolling = input_data_rolling.droplevel('TEAM_ID').reset_index().drop('index', axis=1)

In [637]:
cols = ['OPP_FGM', 'OPP_FGA',
       'OPP_FG_PCT', 'OPP_FG3M', 'OPP_FG3A', 'OPP_FG3_PCT',
       'OPP_FTM', 'OPP_FTA', 'OPP_FT_PCT', 'OPP_OREB',
       'OPP_DREB', 'OPP_REB', 'OPP_AST', 'OPP_STL',
       'OPP_BLK', 'OPP_TOV', 'OPP_PF', 'OPP_PTS']
new_cols = [f"{c}_rolling_15" for c in cols]

input_data_rolling = input_data_rolling.groupby("TEAM_ID").apply(lambda x: rolling_averages(x, cols, new_cols, 15))
input_data_rolling = input_data_rolling.droplevel('TEAM_ID').reset_index().drop('index', axis=1)

input_data = input_data_rolling

In [638]:
input_data.columns

Index(['TEAM_ID', 'TEAM_NAME', 'MATCHUP', 'FGM', 'FGA', 'FG_PCT', 'FG3M',
       'FG3A', 'FG3_PCT', 'FTM',
       ...
       'OPP_FT_PCT_rolling_15', 'OPP_OREB_rolling_15', 'OPP_DREB_rolling_15',
       'OPP_REB_rolling_15', 'OPP_AST_rolling_15', 'OPP_STL_rolling_15',
       'OPP_BLK_rolling_15', 'OPP_TOV_rolling_15', 'OPP_PF_rolling_15',
       'OPP_PTS_rolling_15'],
      dtype='object', length=113)

In [639]:
input_data

,TEAM_ID,TEAM_NAME,MATCHUP,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,OPP_FGM,OPP_FGA,OPP_FG_PCT,OPP_FG3M,OPP_FG3A,OPP_FG3_PCT,OPP_FTM,OPP_FTA,OPP_FT_PCT,OPP_OREB,OPP_DREB,OPP_REB,OPP_AST,OPP_STL,OPP_BLK,OPP_TOV,OPP_PF,OPP_PTS,target,is_home,FGM_rolling_3,FGA_rolling_3,FG_PCT_rolling_3,FG3M_rolling_3,FG3A_rolling_3,FG3_PCT_rolling_3,FTM_rolling_3,FTA_rolling_3,FT_PCT_rolling_3,OREB_rolling_3,DREB_rolling_3,REB_rolling_3,AST_rolling_3,STL_rolling_3,BLK_rolling_3,TOV_rolling_3,PF_rolling_3,PTS_rolling_3,OPP_FGM_rolling_3,OPP_FGA_rolling_3,OPP_FG_PCT_rolling_3,OPP_FG3M_rolling_3,OPP_FG3A_rolling_3,OPP_FG3_PCT_rolling_3,OPP_FTM_rolling_3,OPP_FTA_rolling_3,OPP_FT_PCT_rolling_3,OPP_OREB_rolling_3,OPP_DREB_rolling_3,OPP_REB_rolling_3,OPP_AST_rolling_3,OPP_STL_rolling_3,OPP_BLK_rolling_3,OPP_TOV_rolling_3,OPP_PF_rolling_3,OPP_PTS_rolling_3,FGM_rolling_15,FGA_rolling_15,FG_PCT_rolling_15,FG3M_rolling_15,FG3A_rolling_15,FG3_PCT_rolling_15,FTM_rolling_15,FTA_rolling_15,FT_PCT_rolling_15,OREB_rolling_15,DREB_rolling_15,REB_rolling_15,AST_rolling_15,STL_rolling_15,BLK_rolling_15,TOV_rolling_15,PF_rolling_15,PTS_rolling_15,OPP_FGM_rolling_15,OPP_FGA_rolling_15,OPP_FG_PCT_rolling_15,OPP_FG3M_rolling_15,OPP_FG3A_rolling_15,OPP_FG3_PCT_rolling_15,OPP_FTM_rolling_15,OPP_FTA_rolling_15,OPP_FT_PCT_rolling_15,OPP_OREB_rolling_15,OPP_DREB_rolling_15,OPP_REB_rolling_15,OPP_AST_rolling_15,OPP_STL_rolling_15,OPP_BLK_rolling_15,OPP_TOV_rolling_15,OPP_PF_rolling_15,OPP_PTS_rolling_15
0,1610612755,Philadelphia 76ers,PHL @ CLE,31.0,80.0,0.388,2.0,7.0,0.286,24.0,32.0,0.750,14.0,29.0,43.0,19.0,4.0,1.0,14.0,24.0,88.0,39.0,80.0,0.488,2.0,5.0,0.400,24.0,28.0,0.857,13.0,32.0,45.0,31.0,6.0,8.0,12.0,24.0,104.0,0,0,44.000000,86.000000,0.514667,2.666667,9.000000,0.311000,19.666667,26.000000,0.749667,10.666667,31.666667,42.333333,21.666667,8.666667,5.666667,11.666667,20.333333,110.333333,39.000000,90.333333,0.432667,5.666667,12.333333,0.460667,19.333333,24.666667,0.786000,16.666667,32.333333,49.000000,23.333333,7.000000,4.666667,13.666667,21.000000,103.000000,42.800000,86.266667,0.496800,2.266667,7.666667,0.289733,22.533333,27.933333,0.805533,11.000000,30.200000,41.200000,23.666667,7.800000,4.466667,12.733333,19.333333,110.400000,44.066667,90.800000,0.485333,3.333333,9.000000,0.366000,17.866667,22.733333,0.793200,13.933333,31.733333,45.666667,26.000000,7.533333,4.066667,13.600000,22.066667,109.333333
1,1610612755,Philadelphia 76ers,PHL @ MIL,39.0,79.0,0.494,3.0,5.0,0.600,30.0,39.0,0.769,14.0,24.0,38.0,19.0,8.0,3.0,26.0,20.0,111.0,57.0,96.0,0.594,7.0,14.0,0.500,20.0,25.0,0.800,12.0,25.0,37.0,33.0,13.0,5.0,15.0,27.0,141.0,0,0,38.333333,84.333333,0.455667,2.666667,9.666667,0.273000,23.333333,30.666667,0.759000,11.666667,32.000000,43.666667,20.333333,8.000000,4.666667,12.333333,22.000000,102.666667,38.333333,88.666667,0.434667,5.000000,11.000000,0.446000,21.000000,25.000000,0.837000,15.666667,33.666667,49.333333,25.666667,7.000000,6.000000,14.333333,23.666667,102.666667,41.266667,84.933333,0.486667,2.200000,7.533333,0.286600,22.333333,28.000000,0.797467,11.133333,29.933333,41.066667,22.266667,7.333333,4.400000,12.466667,19.066667,107.066667,43.000000,89.333333,0.481933,3.266667,8.733333,0.370467,17.600000,22.466667,0.792000,14.266667,31.800000,46.066667,25.666667,7.200000,4.533333,13.466667,21.933333,106.866667
2,1610612755,Philadelphia 76ers,PHL vs. NJN,40.0,85.0,0.471,1.0,8.0,0.125,31.0,39.0,0.795,14.0,32.0,46.0,24.0,11.0,10.0,20.0,24.0,112.0,44.0,93.0,0.473,0.0,4.0,0.000,22.0,28.0,0.786,13.0,28.0,41.0,28.0,9.0,3.0,17.0,34.0,110.0,1,1,37.333333,79.333333,0.471333,3.000000,8.000000,0.406333,24.666667,33.000000,0.744333,10.333333,28.666667,39.000000,21.000000,7.333333,2.666667,17.666667,22.000000,102.333333,43.666667,88.000000,0.493333,5.333333,10.666667,0.479333,22.333333,25.666667,0.871667,13.333333,29.666667,43.000000,29.666667,9.333333,5.333333,14.000000,23.666667,115.000000,40.866667,84.600000,0.483867,2.066667,7.200000,0.293267,22.666667,28.666667,0.791267,11.133333,29.666667,40.800000,21.800000,7.133333,4.400000,12.933333,19.333333,106.466667,43.800000,89.933333,0.487067,3.466667,8.733333,0.384733,18.200000,23.333333,0.784200,14.466667,32.000000,46.466667,25.866667,7.400000,4.533333,13.266667,22.333333,109.266667
3,1610612755,Philadelphia 76ers,PHL @ CHI,46.0,82.0,0.561,0.0,4.0,0.000,32.0,37.0,0.865,14.0,34.0,48.0,24.0,6.0,8.0,18.0,19.0,124.0,47.0,101.0,0.465,4.0,12.0,0.333,18.0,23.0,0.783,17.0,22.0,39.0,29.0,14.0,6.0,14.0,25.0,116.0,1,0,36.666667,81.333333,0.451000,2.000000,6.666667,0.337000,28.333333,36.666667,0.771333,14.000000,28.333333,42.333333,20.666667,7.666667,4.666667,20.000000,22.666667,103.666667,46.666667,89.666667,0.518333,3.000000,7.666667,0.300000,22.000000,27.000000,0.814333,12.666667,28.333333,41.000000,30.666667,9.333333,5.333333,14.666667,28.333333,118.333333,40.666667,83.933333,0.485067,2.066667,7.066667,0.294933,23.733333,29.800000,0.798800,11.400000,29.666667,41.066667,21.666667,7.066667,4.800000,13.400000,19.266667,107.133333,43.933333,90.466667,0.485667,3.266667,8.533333,0.356133,18.066667,23.266667,0.781400,14.533333,31.200000,45.733333,25.933333,7.466667,4.333333,13.133333,23.266667,109.200000
4,1610612755,Philadelphia 76ers,PHL vs. WAS,44.0,84.0,0.524,0.0,4.0,0.000,23.0,28.0,0.821,13.0,39.0,52.0,33.0,10.0,12.0,22.0,13.0,111.0,48.0,105.0,0.457,1.0,7.0,0.143,7.0,11.0,0.636,16.0,23.0,39.0,27.0,18.0,4.0,14.0,23.0,104.0,1,1,41.666667,82.000000,0.508667,1.333333,5.666667,0.241667,31.000000,38.333333,0.809667,14.000000,30.000000,44.000000,22.333333,8.333333,7.000000,21.333333,21.000000,115.666667,49.333333,96.666667,0.510667,3.666667,10.000000,0.277667,20.000000,25.333333,0.789667,14.000000,25.000000,39.000000,30.000000,12.000000,4.666667,15.333333,28.666667,122.333333,41.066667,83.866667,0.490333,1.933333,6.666667,0.281600,24.733333,30.866667,0.802467,11.800000,30.266667,42.066667,21.800000,7.000000,5.200000,13.600000,19.400000,108.800000,43.466667,90.733333,0.479533,3.333333,8.800000,0.353333,18.200000,23.466667,0.780267,14.666667,30.266667,44.933333,25.666667,7.933333,4.600000,13.066667,23.866667,108.466667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2640,1610612755,Philadelphia 76ers,PHI @ TOR,47.0,81.0,0.580,16.0,40.0,0.400,22.0,23.0,0.957,10.0,37.0,47.0,32.0,4.0,4.0,11.0,22.0,132.0,35.0,89.0,0.393,7.0,35.0,0.200,20.0,25.0,0.800,15.0,22.0,37.0,15.0,6.0,1.0,10.0,22.0,97.0,1,0,34.666667,76.666667,0.453333,10.000000,32.333333,0.309333,18.666667,21.333333,0.876000,7.333333,30.666667,38.000000,19.000000,7.000000,4.333333,14.666667,22.000000,98.000000,35.666667,82.333333,0.433000,10.000000,31.666667,0.322000,20.000000,24.333333,0.833333,11.333333,31.000000,42.333333,20.000000,7.000000,2.000000,13.333333,20.666667,101.333333,38.133333,84.600000,0.452867,10.533333,30.400000,0.352933,17.800000,21.533333,0.827867,8.800000,33.200000,42.000000,22.333333,8.200000,5.200000,13.266667,19.666667,104.600000,39.533333,86.333333,0.458667,12.000000,32.800000,0.366933,15.533333,19.733333,0.778600,9.866667,35.266667,45.133333,23.333333,6.533333,4.933333,13.466667,19.866667,106.600000
2641,1610612755,Philadelphia 76ers,PHI @ TOR,38.0,74.0,0.514,13.0,31.0,0.419,15.0,20.0,0.750,9.0,37.0,46.0,18.0,5.0,3.0,24.0,21.0,104.0,38.0,86.0,0.442,13.0,35.0,0.371,12.0,18.0,0.667,9.0,23.0,32.0,23.0,9.0,4.0,11.0,21.0,101.0,1,0,39.666667,81.333333,0.487333,10.000000,34.666667,0.281000,19.666667,21.666667,0.907000,8.000000,31.333333,39.333333,22.333333,6.000000,4.666667,12.000000,21.333333,109.000000,38.333333,86.333333,0.447000,10.000000,33.333333,0.311000,20.666667,24.666667,0.850000,12.666667,30.000000,42.666667,20.333333,5.333333,2.000000,12.333333,20.666667,107.333333,39.066667,84.066667,0.466800,11.066667,31.000000,0.362400,18.400000,21.933333,0.840667,8.933333,33.133333,42.066667,23.133333,8.000000,4.866667,13.533333,20.000000,107.600000,39.666667,87.000000,0.457000,11.733333,33.266667,0.354067,16.133333,20.400000,0.783067,10.600000,33.933333,44.533333,23.133333,6.600000,4.466667,13.266667,20.333333,107.200000
2642,1610612755,Philadelphia 76ers,PHI vs. TOR,36.0,69.0,0.522,14.0,30.0,0.467,26.0,30.0,0.867,7.0,34.0,41.0,20.0,5.0,12.0,16.0,18.0,112.0,38.0,89.0,0.427,11.0,32.0,0.344,10.0,12.0,0.833,13.0,22.0,35.0,16.0,7.0,4.0,11.0,24.0,97.0,1,1,39.666667,78.000000,0.508000,11.666667,35.000000,0.331667,18.333333,21.000000,0.869000,9.333333,34.000000,43.333333,22.666667,4.333333,4.333333,16.666667,20.000000,109.333333,37.666667,89.000000,0.423333,9.666667,35.333333,0.273667,16.333333,20.333333,0.803667,13.000000,25.666667,38.666667,19.666667,6.666667,2.333333,11.333333,20.333333,101.333333,39.000000,82.533333,0.474267,11.266667,30.866667,0.370133,18.533333,22.066667,0.842533,8.733333,32.733333,41.466667,22.733333,7.866667,4.666667,14.400000,20.133333,107.800000,39.733333,86.733333,0.459067,12.066667,33.400000,0.362667,16.000000,20.400000,0.775667,10.666667,32.333333,43.000000,23.333333,6.733333,4.333333,13.200000,20.333333,107.533333
2643,1610612755,Philadelphia 76ers,PHI vs. TOR,43.0,84.0,0.512,16.0,32.0,0.500,29.0,34.0,0.853,10.0,29.0,39.0,29.0,6.0,4.0,4.0,18.0,131.0,40.0,82.0,0.488,12.0,30.0,0.400,19.0,23.0,0.826,7.0,29.0,36.0,27.0,1.0,8.0,8.0,26.0,111.0,1,1,40.333333,74.666667,0.538667,14.333333,33.666667,0.428667,21.000000,24.333333,0.858000,8.666667,36.000000,44.666667,23.333333,4.666667,6.333333,17.000000,20.333333,116.000000,37.000000,88.000000,0.420667,10.333333,34.000000,0.305000,14.000000,18.333333,0.766667,12.333333,22.333333,34.666667,18.000000,7.333333,3.000000,10.666667,22.333333,98.333333,38.800000,80.933333,0.481133,11.400000,30.600000,0.377733,18.266667,21.466667,0.849067,8.400000,32.866667,41.266667,22.266667,7.333333,5.133333,14.400000,19.666667,107.266667,39.066667,86.266667,0.454200,11.866667,33.133333,0.359667,15.933333,20.133333,0.785333,10.800000,30.933333,41.733333,22.933333,6.733333,4.200000,12.533333,19.866667,105.933333
2644,1610612755,Philadelphia 76ers,Philadelphia 76ers @ Miami Heat,39.4,84.5,0.466,11.6,31.8,0.364,19.6,23.8,0.821,8.5,33.8,42.3,23.7,7.7,5.3,12.5,19.4,109.9,39.6,84.8,0.467,13.6,35.8,0.379,17.3,21.4,0.808,9.8,33.9,43.7,25.5,7.4,3.2,14.6,20.5,110.0,0,1,39.000000,75.666667,0.516000,14.333333,31.000000,0.462000,23.333333,28.000000,0.823333,8.666667,33.333333,42.000000,22.333333,5.333333,6.333333,14.666667,19.000000,115.666667,38.666667,85.666667,0.452333,12.000000,32.333333,0.371667,13.666667,17.666667,0.775333,9.666667,24.666667,34.333333,22.000000,5.666667,5.333333,10.000000,23.666667,103.000000,39.400000,81.200000,0.486933,11.933333,30.866667,0.392000,18.866667,22.266667,0.845333,8.533333,32.600000,41.133333,23.066667,7.066667,4.933333,13.266667,19.400000,109.600000,38.933333,86.400000,0.451733,11.666667,32.600000,0.360000,16.066667,20.066667,0.793200,11.000000,30.400000,41.400000,22.600000,6.333333,4.400000,12.000000,20.200000,105.600000

In [640]:
input_data = input_data.iloc[-1]

In [641]:
prediction = make_predictions(input_data, predictors, rf)

In [642]:
prediction

TEAM_NAME                  Philadelphia 76ers
MATCHUP       Philadelphia 76ers @ Miami Heat
Prediction                                  W
Name: 2644, dtype: object

In [643]:
def make_predictions_logregress(data, predictors, model):

    values = [data[predictors].values]
    prediction = model.predict(values)[0]
    prediction_prob = model.predict_proba(values)[0]
    
    prediction_df = data[["TEAM_NAME","MATCHUP"]]
    if prediction == 0:
        prediction_df["Prediction"] = "L"
    else:
        prediction_df["Prediction"] = "W"
    prediction_df["Prediction Probability"] = prediction_prob
    
    
    return prediction_df, prediction

In [644]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(solver='liblinear',random_state=1)

combined, precision, results, lr = train_test_model(rolling_df, predictors, lr)

In [645]:
combined

,actual,prediction,GAME_DATE,TEAM_NAME,OPP_TEAM_NAME,WL
2593,1,1,2021-10-21T00:00:00,Atlanta Hawks,Dallas Mavericks,W
2594,0,0,2021-10-23T00:00:00,Atlanta Hawks,Cleveland Cavaliers,L
2595,1,1,2021-10-25T00:00:00,Atlanta Hawks,Detroit Pistons,W
2596,1,0,2021-10-27T00:00:00,Atlanta Hawks,New Orleans Pelicans,W
2597,0,0,2021-10-28T00:00:00,Atlanta Hawks,Washington Wizards,L
...,...,...,...,...,...,...
77391,0,0,2022-04-02T00:00:00,Charlotte Hornets,Philadelphia 76ers,L
77392,0,1,2022-04-05T00:00:00,Charlotte Hornets,Miami Heat,L
77393,1,1,2022-04-07T00:00:00,Charlotte Hornets,Orlando Magic,W
77394,1,1,2022-04-08T00:00:00,Charlotte Hornets,Chicago Bulls,W
77395,1,1,2022-04-10T00:00:00,Charlotte Hornets,Washington Wizards,W

In [646]:
precision

0.5840433772269559

In [647]:
results

prediction    0    1
actual
0           752  537
1           535  754

In [648]:
prediction = make_predictions_logregress(input_data, predictors, lr)

In [649]:
prediction

(TEAM_NAME                                        Philadelphia 76ers
 MATCHUP                             Philadelphia 76ers @ Miami Heat
 Prediction                                                        W
 Prediction Probability    [0.31385291611414257, 0.6861470838858574]
 Name: 2644, dtype: object,
 1)